### ISSUE TITLE
Git blame status bar info disappears on 7.0.0

### ISSUE THREAD

**Issue by benjreinhart** [Sertion/vscode-gitblame#101]
### Description

After upgrading to 7.0.0, the git blame in VSCode status bar disappears on my repositories.

I tried quitting and restarting VSCode, disabling/enabling, and uninstalling/reinstalling the extension.

### 6.0.2

<img width="1100" alt="Screen Shot 2021-05-07 at 4 34 27 PM" src="https://user-images.githubusercontent.com/606233/117517842-38335780-af52-11eb-9914-0d60d3aa2b88.png">

### 7.0.0

<img width="1178" alt="Screen Shot 2021-05-07 at 4 37 25 PM" src="https://user-images.githubusercontent.com/606233/117517916-89dbe200-af52-11eb-9a17-c49cdf2cc1f9.png">

### Info

VSCode version: **1.56.0 (Universal)**
MacOS version: **10.15.7 macOS Catalina**
Git version: **git version 2.24.3 (Apple Git-128)**

**Comment by Sertion** [comment]
Hey Ben! Thank you for the bug report.

I have found the issue and have uploaded a new version. It sometimes takes a few moments for it to verify, but should be available  shortly.

**Comment by benjreinhart** [comment]
Sweeeet, thank you @Sertion !
