### ISSUE TITLE
Quick link not working

### ISSUE THREAD

**Issue by RicardoFariaSilva** [Sertion/vscode-gitblame#103]
Hello guys,

My VSCode was updated recently to 1.56 and the extension it's not working properly anymore. Commits are shown, but when a click on it the link do GitHub does not work.

Can I help you with some more info?

Thanks in advance.

**Comment by Sertion** [comment]
Hey Ricardo. Thank you for reporting a bug!

I think I have found the cause and will try to find a solution.

It has the same root cause as #102.

**Comment by Sertion** [comment]
I have found the issue and patched it. A new version (7.0.4) should be available for download soon.
