### ISSUE TITLE
The Copy button is gone

### ISSUE THREAD

**Issue by a1291762** [Sertion/vscode-gitblame#106]
The Copy button is gone, which is a problem for me.

I need to transfer the URL into a private browser window. Clicking Copy let me do this.

Clicking View opens a non-private browser window, which immediately changes the URL, making it impossible to copy the URL.

**Comment by a1291762** [comment]
FWIW: This is what I see now: 
![image](https://user-images.githubusercontent.com/327162/123567007-89e6b880-d804-11eb-9b59-4e7e8a2381ff.png)
I don't know how to get a screenshot from before, but there was a Copy button there.

**Comment by a1291762** [comment]
I wonder... if the recent "Trust" change in vscode is the root cause here?
I never added sites to the "Trusted Domains" config and I see it's still empty, but I did trust the folder I have open...

**Comment by a1291762** [comment]
yeah... nevermind, it's a vscode bug.
untrusted folder that's allowed to use the git blame extension uses trusted domains.
![image](https://user-images.githubusercontent.com/327162/123568678-2bbbd480-d808-11eb-9ed7-8b133d9e2a83.png)

**Comment by Sertion** [comment]
This flew under my radar. I am sorry.

There is a command for copying the URL generated by vscode-gitblame. If you use the command palette it is called `Git Blame: Copy tool URL to clipboard` and if you want to bind it to a keyboard shortcut it is called `gitblame.addToolUrlToClipboard`.

I hope you have good URL copying experiences!
