### ISSUE TITLE
Setting to switch status bar side

### ISSUE THREAD

**Issue by joaomoreno** [Sertion/vscode-gitblame#107]
Usually, editor line-dependent status bar contributions are supposed to be on the right-hand side of the statusbar. It's very odd that this one sits on the left. Switching the default by now would upset users, so I suggest to add a setting.

**Comment by Sertion** [comment]
Hey João!

Thank you for the feature request. I'm working on a new version right now. I will see if I can add this to it.

**Comment by Sertion** [comment]
A new version with this feature was released yesterday. I hope it works as you expect!

**Comment by joaomoreno** [comment]
Thanks! Here's your reward 🥇 https://github.com/Sertion/vscode-gitblame/pull/112
