### ISSUE TITLE
Setting to change default click action

### ISSUE THREAD

**Issue by joaomoreno** [Sertion/vscode-gitblame#108]
Clicking the status bar item now simply shows a notification. I want to directly open the link on GitHub 100% of the time. Switching the default by now would upset users, so I suggest to add a new setting to switch the default click action.

**Comment by Sertion** [comment]
Hey João!

Thank you for the feature request. I'm working on a new version right now. I will see if I can add this to it.

**Comment by Sertion** [comment]
A new version with this feature was released yesterday. I hope it works as you expect!
