### ISSUE TITLE
${gitorigin.path,n} returns 'invalid-index'

### ISSUE THREAD

**Issue by harri-halttunen-aktia** [Sertion/vscode-gitblame#110]
`${gitorigin.path,n}` seems to fail when `git ls-remote --get-url` command returns URL like this:
* `ssh://git@git.company.com/project_x/test-repository.git`

`${gitorigin.path,n}` returns 'invalid-index' no matter what `n` is.

As a side note, my goal is to build a Git URL like this:
* `https://git.company.com/projects/project_x/repos/test-repository/commits/8477f804daea99e6738b14c7a95e080265412abe`

**Comment by Sertion** [comment]
Hey harri-halttunen-aktia!

Thank you for reporting this. Will look into it.

**Comment by Sertion** [comment]
I'm currently working on a new version (8) that will change a bit how the `gitorigin.path` token behaves. Does the token resolves in [the added test here look like you expect](https://github.com/Sertion/vscode-gitblame/commit/2aab8a5fe7bedcb371f8ea2ab6d448d6beaf9872#diff-2763e0e5897a62fed9c958e6e650ba0347836a63a7ba21254dfa715f66abb6ecR165)?

**Comment by harri-halttunen-aktia** [comment]
The test almost looks like what is needed. I would use this URL as an additional test case:
* `ssh://git@git.company.com/project_x/test-repository.git`
as it contains both, dash (-) and underscore (_) characters. Also, it has a subdomain (not that it necessarily matter).

**Comment by Sertion** [comment]
I've released a new version that should solve this problem. It will appear sometime soon™.
