### ISSUE TITLE
Git-Blame shows Chinese instead of English

### ISSUE THREAD

**Issue by AmosChenYQ** [Sertion/vscode-gitblame#111]
Issue Type: <b>Bug</b>

Git-Blame shows Chinese instead of English
I have set my VS-Code display language to English, and my system git-cli, cmd, powershell are all in English, why it shows Chinese git blame message like "23天前" instead of "23 days ago"?

![image](https://user-images.githubusercontent.com/31386769/125908001-c089e8d6-661a-4e3f-8be7-2576c2e93621.png)

Extension version: 8.0.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.83GB free)|
|Process Argv|--crash-reporter-id e6caf0ac-512f-403c-bfea-b46f17e267ba --crash-reporter-id e6caf0ac-512f-403c-bfea-b46f17e267ba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by AmosChenYQ** [comment]
BTW, Git-Blame was showing English before I upgrading my VSCode

**Comment by AmosChenYQ** [comment]
I have read your recently CHANGELOG, seems to be caused by new feature...

**Comment by AmosChenYQ** [comment]
After I install 7.0.6, everything is OK. I think you should add a config to choose whether use 
```md
Breaking change: Using Intl.RelativeTimeFormat to get relative time messages. This will change some things in the output:
```

**Comment by Sertion** [comment]
Hey AmosChenYQ!

It should use your computers default locale. I will change it so that it uses the vscode locale instead.

**Comment by wenfangdu** [comment]
Confirmed, changed to Chinese after upgrading to v8.0.0.

**Comment by Sertion** [comment]
A new version has been uploaded to the marketplace. It sometimes can take a few minutes/hours for it to appear.

**Comment by wenfangdu** [comment]
@Sertion Tried it, back to English now, thanks.

**Comment by AmosChenYQ** [comment]
![image](https://user-images.githubusercontent.com/31386769/125955996-475c733e-2a65-433d-bc66-e7d310fa2fc1.png)
Solved. Thanks for your quick response!
