### ISSUE TITLE
[Feature Request] Add support for "git blame --reverse"

### ISSUE THREAD

**Issue by tommai78101** [Sertion/vscode-gitblame#113]
In Git Blame, there's an option to run `--reverse` by specifying 2 commit IDs and target a specific file. Since the current Git Blame extension can target specific file via the currently opened / viewed document, I believed it should all work the same here.

The syntax for `git blame --reverse` is:

`git blame --reverse START..END`

> Walk history forward instead of backward. Instead of showing the revision in which a line appeared, this shows the last revision in which a line has existed. This requires a range of revision like START..END where the path to blame exists in START. git blame --reverse START is taken as git blame --reverse START..HEAD for convenience. START and END are revisions.

Source:  https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-blame.html

I would like to request for this VS Code extension to add support for `git blame --reverse`.

Thanks.

**Comment by Sertion** [comment]
Hey Thompson! Thank you for the feature request!

How do you see this working? Should the status bar show information from the earliest commit where it now shows from the oldest commit or should it be a command you can run to see info for the oldest commit in an info message?

The largest issue I can see with making it toggelable is that today everything expects there to only be one blame per line and toggling between two sets would either require a lot of rewrites or a reblame after each toggle. Some blames can take minutes on larger git repos so I would like to avoid that.

**Comment by tommai78101** [comment]
There would be a way for the user to enter in 2 revision or commit IDs. The END by default would be HEAD.

And then once the user clicks "Search" or "OK" or some button, it runs `git blame --reverse` based on the entered arguments, and then displays the results.

**Comment by Sertion** [comment]
I have given this some thought and I feel it is out of scope for the extension.

It does sound like a good candidate for a new extension if anyone is up for the task.
