### ISSUE TITLE
Execute command to query gerrit for url to code review website

### ISSUE THREAD

**Issue by sparlund** [Sertion/vscode-gitblame#114]
I use Gerrit for code reviews in a project. I'm not an expert at how Gerrit works, but to find the correct code review URL for the website you can/need to query Gerrit. See below, $username, $hostname and $hash should be self explanatory.
`ssh -p 29418 $username@$hostname gerrit query --current-patch-set $hash | grep "url" | sed -e 's/  url: //g'`

This returns an URL for the code review user interface.

Could this somehow be incorporated into this extension? I don't want to use the commit hash-id, but rather what Gerrit calls the "number" [1]. 

If it doesn't really fit the purpose of the extension, could you point me in the general direction in the code base where I could start fiddling with my own fork? 

Thanks in advance and cheers for a great extension.

[1] https://gerrit-review.googlesource.com/Documentation/json.html#patchSet

**Comment by Sertion** [comment]
Hey sparlund!

As you have identified yourself this is out of scope for the extension.

The [Extension Anatomy-page](https://code.visualstudio.com/api/get-started/extension-anatomy) is a good overview of what an extension is and how they register commands. In this particular case I don't know what data you would need from the vscode-gitblame but all commands are registered in the [index-file](https://github.com/Sertion/vscode-gitblame/blob/master/src/index.ts). From there it is pretty straight forward async/await stuff.
