### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sourav-Sonkar** [Sertion/vscode-gitblame#116]
- Issue Type: `Performance`
- Extension Name: `gitblame`
- Extension Version: `8.1.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Sourav\AppData\Local\Temp\waderyan.gitblame-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Sertion** [comment]
Can't do anything about these without the cpuprofile.txt.
