### ISSUE TITLE
commit.summary before commit.hash_short causes display bug

### ISSUE THREAD

**Issue by Cathryne** [Sertion/vscode-gitblame#119]
Hello & 1k thanks for this neat extension :-)

As Adam in https://github.com/Sertion/vscode-gitblame/issues/94#issuecomment-718127930, I also migrated off GitLens found a new home here!

Possibly, I have stumbled upon a little bug in the `gitblame.statusBarMessageFormat` parsing or display: It doesn't seem possible to have `commit.summary` _before_ `commit.hash_short` _and_ have both displayed in that order:

![vsc-gitblame-summary-bug](https://user-images.githubusercontent.com/757323/153708363-d1cf4f66-c1d2-4843-a526-07e6dd75b41f.gif)

All the other fields I've tried get rendered as expected, and I also tried it with all other VSCode settings removed. Only that `${commit.summary} ${commit.hash_short,7}` combination/order seems to cause the former to be unexpectedly hidden.

<details><summary>Env info</summary>
<pre>
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-11T00:29:32.407Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0 (macOS Catalina 10.15.7)
</pre>
</details>

**Comment by Sertion** [comment]
Hello Cathryne!

Fascinating bug! I have been able to recreate it.

Sadly I have no idea when I will have the time to look into it at any length.
