### ISSUE TITLE
Errors get logged to console when directory is not using git

### ISSUE THREAD

**Issue by Abromeit** [Sertion/vscode-gitblame#124]
Steps to reproduce: 

- Open any directory in VS Code, which is not contained in a git project. For example, open your desktop directory.
- Now open any text-based file. For example `[…]/Desktop/foo.txt`.

&nbsp;

At this point your VS Code devtools console will contain messages like the following:

<img width="1244" alt="screenshot1" src="https://user-images.githubusercontent.com/537920/171416423-2f3f2171-00d6-4b26-9f5f-715ad20fac40.png">

&nbsp;

Expected behaviour:

- Errors like these should get catched and handled silently.
- The extension should not constantly retry failed file system actions. (E.g. opening/watching the file `[curdir]/HEAD`.)

&nbsp;

My Environment: 

- VSCode 1.67.2
- Git Blame Extension v8.2.1 
- macOS 12.4 on Intel Chip

&nbsp;

_Thanks a lot for the time you're investing – This extension is a great help for maintaining old code bases!_<br />&nbsp;

**Comment by Sertion** [comment]
Hello Daniel! Thank you for the great issue.

If you think you can fix it I would love a PR but otherwise I can probably spend a few minutes on it quite soon.

**Comment by Sertion** [comment]
I have uploaded a new version to the marketplace. It can sometimes take a day or two before it updates.
