### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Verlong** [Sertion/vscode-gitblame#126]
- Issue Type: `Performance`
- Extension Name: `gitblame`
- Extension Version: `8.2.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/bonko/AppData/Local/Temp/waderyan.gitblame-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Sertion** [comment]
Hey Verlong.

Sadly I am unable to do anything about this report without the file vscode says you should attach.
