### ISSUE TITLE
Icon to see git blame no longer showing in status bar

### ISSUE THREAD

**Issue by marywelch-chief** [Sertion/vscode-gitblame#130]
I have git blame installed as an extension in VS code, but I no longer see the icon in the status bar so I don't know how to use it anymore. :-(

**Comment by Sertion** [comment]
Hey marywelch-chief!

The extension recently moved from the left side of the status bar to the right side. This change was done to better reflect what vscode intends the two sides to be related to: left is project information and right is for the current file/selection.

It is also possible that you have disabled the status bar item. To check if it has been disabled right click on the status bar and make sure that _Git Blame (Extension)_ has a checkmark.

**Comment by schoinh** [comment]
@marywelch-chief Thank you for asking this question, I thought it was gone, too!

**Comment by alliha** [comment]
I seem to be having a similar problem, but I do have my git blame enabled. 

![bilde](https://user-images.githubusercontent.com/10848252/185601398-15f8d787-2d8f-4268-ad55-2d7dcb11f105.png)

**Comment by Sertion** [comment]
Hey Alfred. Thank you for the screenshot! In this specific case the extension is hidden as there is no space for it to display. If you change the priority (`gitblame.statusBarPositionPriority`), disable some other items, or make the window wider somehow it should return.

**Comment by marywelch-chief** [comment]
I was able to see it again once I got vs code on a really big screen...
thank you for the tip on where to look for it.
