### ISSUE TITLE
Support newlines in info message format

### ISSUE THREAD

**Issue by gamma032steam** [Sertion/vscode-gitblame#131]
**Expected behaviour:**
Setting `"gitblame.infoMessageFormat": "${commit.hash}\n${commit.summary}"`
should display the hash and summary on separate lines. This should also work for `\r\n`.

**Actual behaviour:**
The `\n` is swallowed up. Hash and summary appear on the same line.
![image](https://user-images.githubusercontent.com/7892801/185067581-c5ec5ad9-d2b2-4247-a257-1b7373c59965.png)

**Comment by Sertion** [comment]
Hey Matthew. Thank you for the issue!

Sadly [this is not possible with the vscode API](https://github.com/Microsoft/vscode/issues/48900).

**Comment by Sertion** [comment]
Hey Matthew. Thank you for the issue!

Sadly [this is not possible with the vscode API](https://github.com/Microsoft/vscode/issues/48900).
