### ISSUE TITLE
Git Blame stopped showing info

### ISSUE THREAD

**Issue by arielWix** [Sertion/vscode-gitblame#132]
I used this extension for while and it worked before but it seems that its not longer showing blame info.
I do have the GotBlame Icon but when hovering it I see tooltip saying "Git Blame - no info about the current line", any idea why?

BTW - it seems that I do see `blame` data for files in the monorepo root folder but not for the internal projects  

This looks weird: 🤔 
![image](https://user-images.githubusercontent.com/89974079/193531415-03c46909-33d3-4226-b2b9-f8b9e2bbbb7a.png)

**Comment by Sertion** [comment]
Hey arielWix!

Sadly this is not enough information for me to have a clear answer.

Have you looked in the _Output_ > _Git Blame_ log? Does it help you?

To see what git folder the extension uses you can `cd` to the folder where a file you want to blame is and run `git rev-parse --git-dir`.

**Comment by arielWix** [comment]
not much in the logs:

```
[ 23:05:43 | command ] /usr/local/bin/git rev-parse --git-dir
[ 23:05:44 | command ] /usr/local/bin/git blame -C --incremental -- /Users/arielh/Git/metro/packages/http-client-testkit/src/http-mock-server.ts
[ 23:05:44 | info ] Blamed "/Users/arielh/Git/metro/packages/http-client-testkit/src/http-mock-server.ts"
[ 23:06:03 | command ] /usr/local/bin/git rev-parse --git-dir
[ 23:06:03 | command ] /usr/local/bin/git rev-parse --git-dir
[ 23:06:03 | command ] /usr/local/bin/git blame -C --incremental -- /Users/arielh/Git/metro/packages/http-client-testkit/src/http-status.ts
[ 23:06:03 | info ] Blamed "/Users/arielh/Git/metro/packages/http-client-testkit/src/http-status.ts"
[ 23:07:49 | command ] /usr/local/bin/git rev-parse --git-dir
[ 23:07:49 | command ] /usr/local/bin/git blame -C --incremental -- /Users/arielh/Git/metro/packages/http-client-testkit/src/utils.ts
[ 23:07:50 | info ] Blamed "/Users/arielh/Git/metro/packages/http-client-testkit/src/utils.ts"
```

**Comment by Sertion** [comment]
Thank you for the log output!

If it gets as far as the info message about blaming files it _should_ work all the way from there. When things break it is usually between the extension and git or the filesystem. Here it is past all that and whats rest is only display logic.

Does _the internal projects_ have settings specific to them? If it has they should be located in [`.vscode/settings.json`](https://code.visualstudio.com/docs/editor/workspaces#_workspace-settings).

**Comment by arielWix** [comment]
After I noticed that other projects do show blame data properly I tried to delete the whole repository and re-cloned it, now I see the data again :)
