### ISSUE TITLE
RFE: ability to launch a command instead of triggering an URL

### ISSUE THREAD

**Issue by mikkorantalainen** [Sertion/vscode-gitblame#133]
I sometimes need to dig history more to inspect the source after seeing a line in the editor. Right now the popup contains button "View" which triggers the URL to open with your default browser.

How about adding an ability to execute a command? I would set it to something like

    git gui blame --line=${file.line.result} -- ${file.path}

because git gui blame has great features to got back in history for a single line or nearby context as needed.

**Comment by Sertion** [comment]
Hey Mikko! Thank you for the feature request.

Where should the command be executed and should it replace the online link with the command?

**Comment by MKHMN** [comment]
It is also would be great to be able to open the diff in the vscode itself.

**Comment by Sertion** [comment]
Hey MKHMN. That sounds like a separate feature request and one that is out of scope.

If you are looking for a git blame extension with a lot more features I think [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) is the most feature rich one. I have not used it myself and I do not know if it can show git diffs in editor.

**Comment by J-Sorenson** [comment]
GitLens has become a tad glitchy in recent releases, and too many features are starting to become redundant with bult-in VS Code features.  I suggest accompanying this GitBlame extension with [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) when you want to see changes in a file with the VS Code diff engine. The two extensions work together quite nicely.  I'm starting to realize that any extension that tries to be "all the things" will quickly become bloated and unreliable.

**Comment by Sertion** [comment]
Sadly it is not (currently) possible to do line breaks in (`window.showInformationMessage`)[https://code.visualstudio.com/api/references/vscode-api#window.showInformationMessage]. The options to [display content](https://code.visualstudio.com/api/references/vscode-api#window.createInputBox) in a non-intrusive way in vscode is currently a bit limited.

**Comment by Sertion** [comment]
After some thinking I've decided against allowing running a custom command from with in the extension, too many things to take into consideration surrounding it.

I've instead added the ability to run `git show` for the commit in the vscode build in terminal instead. I hope this fulfills the basics of the needs expressed in this issue.

The feature should be available in 10.4.0.
