### ISSUE TITLE
Master or Main

### ISSUE THREAD

**Issue by elcortez** [Sertion/vscode-gitblame#134]
Hello, I'm using this great VS Code extension in order to open the specific file at the specific line in the master or main branch (basically what Atom does when you type CMD+MAJ+P & type "Blame")

[Per your instructions](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame), I've managed to make the extension open it with this commit url
`${tool.protocol}//${gitorigin.hostname}${gitorigin.port}/${gitorigin.path}/blame/master/${file.path}#L${file.line}`

However, I had to write "master" in plain text, for I don't see this option in the instructions, therefore it does not work on repositories that have a "main" branch instead of "master".
It would be really AWESOME if you could make it work ! <3

**Comment by Sertion** [comment]
Hey Pierre! Thank you for the feature request.

That looks like something that could be added to [the token generator](https://github.com/Sertion/vscode-gitblame/blob/044e263593b9d4be2ba1eadad1aad6c39ae7d03e/src/git/util/get-tool-url.ts#L77).

If you want to give it a go I accept pull requests or I will get to it when I have the time.

**Comment by elcortez** [comment]
Hello, thanks for your answer, I would love to try, but I'm kind of a newbie in typescript. 
Can you point me to some link  where I can learn how to properly test the app or maybe give me a command to run on my terminal to run the tests ?

**Comment by Sertion** [comment]
If you use vscode as your editor you should be able to run _Extension_ and _Test Extension_ from the [_Run and Debug_](https://code.visualstudio.com/Docs/editor/debugging) menu in the sidebar. [Here is an example of some tests for the token generator](https://github.com/Sertion/vscode-gitblame/blob/044e263593b9d4be2ba1eadad1aad6c39ae7d03e/test/suite/generate-url-tokens.test.ts#L43) with some (unfortunately needed) mocking.

**Comment by Sertion** [comment]
I had some time over the Easter break and built this. It will be part of 10.2.0. The token is called `${project.defaultbranch}`
