### ISSUE TITLE
Potentially causing system / device connectivity issues

### ISSUE THREAD

**Issue by ThoseGrapefruits** [Sertion/vscode-gitblame#137]
Type: <b>Bug</b>

I'm running VSCode on latest macOS (13.2.1) on a MacBook Air. I've been experiencing some weird system issues, which seem impossible to relate to this plugin, but stick with me.

I have been experiencing issues with an Apple Studio Display plugged in which have been kinda mysterious. After ~10 minutes of working in VSCode, the display starts disconnecting randomly every few seconds. I wasn't 100% sure it was VSCode at first but after much fussing around and waiting and doing other things, it _only_ happens when VSCode is open. So, I started a plugin bisect to try to figure out if a plugin was somehow related. That bisect landed on this one, and once it was disabled, I haven't experienced that issue once and I've been actively editing code for well over an hour.

I believe I was having issues when I first got the Studio Display, and it's the first time I've had anything like that happen with it. I'm still not 100% sure that this plugin is to blame (heh) but I figured I'd post here anyways in case someone else is experiencing something similar.

I'll keep ya posted if I do encounter the issue again while this plugin is disabled.

Extension version: 10.1.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv|--crash-reporter-id c074cf48-a0cf-4267-9784-90cd2b2ed7f3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982
vscodedisable:30660115

```

</details>

**Comment by Sertion** [comment]
Hey Logan. Thanks for the report.

"All" the extension does it to call `git` a bunch of times. If you want to test running `git blame` [a few times in your terminal](https://unix.stackexchange.com/questions/10646/repeat-a-unix-command-every-x-seconds-forever) does the same thing happen?

**Comment by ThoseGrapefruits** [comment]
Thanks for the info! Ok it was indeed too weird to be true. I did try running git a bunch of times and it was fine. Turns out its iTerm2's GPU rendering, which is what I suspected early on, but I was led astray by something else :)

Thanks for your time! Have a great rest of your week.

**Comment by Sertion** [comment]
What a relief! Thank you for the prompt investigation and report back!
