### ISSUE TITLE
Extension does do anything when clicking on bottom bar button

### ISSUE THREAD

**Issue by alexgille** [Sertion/vscode-gitblame#138]
Hi,

The extension used to work but isn't anymore since few weeks.
Clicking on the "Blame XXX (Y Z ago)" has not effect at all, except showing "Waiting for [...]" very fast (too fast to read).

A brand new install of the extension did nothing to the issue, neither did restarting VSCode.

VSCode details :
```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```
And `git version 2.37.0`

Thanks

**Comment by Sertion** [comment]
Hey Alexandre! Thanks for the report.

Do you know if you have set any setting that modify the default behavior of the extension? Can you also please verify that it is this extension that you interact with and not another one like [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)?

Last update was a few months ago so it is a bit weird that the behavior is changing now. Do you know if you recently updated git?

**Comment by alexgille** [comment]
I haven't changed anything on my setup since, except VSCode updates, and I don't configure VSCode with particular settings. This extension is the only one I use related to Git.

I forgot to mention that I've been facing this issue for weeks (but not months), maybe related to the latest update.

**Comment by Sertion** [comment]
I've looked some more and I can't see anything obvious that is wrong. Does the line have blame info if you run `git blame -- FILE_PATH`?

If you want to look into what could be wrong yourself I would appreciate it a lot.

It should be possible to [debug the extension from within vscode](https://code.visualstudio.com/Docs/editor/debugging) by setting breakpoints and running the "Extension" setup from the _Run and Debug_ options.

The default action from pressing the status bar view when the extension has found a commit for the current line is [Extension.showMessage](https://github.com/Sertion/vscode-gitblame/blob/9a3d6c3bd9e92fd0bdfa6000302c9b6c2aed5ddc/src/git/extension.ts#L61). The brief flash of "Waiting for git blame response" you see comes from the `this.view.activity()` call in [Extension.commit](https://github.com/Sertion/vscode-gitblame/blob/9a3d6c3bd9e92fd0bdfa6000302c9b6c2aed5ddc/src/git/extension.ts#L176).

If the extension is showing blame information for a line in the status bar it should be available in the [`Blamer`](https://github.com/Sertion/vscode-gitblame/blob/9a3d6c3bd9e92fd0bdfa6000302c9b6c2aed5ddc/src/git/blame.ts) and it should not be able to miss finding it a second time.

**Comment by MKHokinson** [comment]
Hey @alexgille, I was having the same issue with this and a few other extensions. After an embarrassing amount of time spent faffing about with them and debugging this extension, it appears that the popup windows act as notifications. I had disabled the popup notifications in the bottom right, hence causing this extension and others to "stop working". You should be able to check by hitting the bell in the lower right hand corner.

**Comment by alexgille** [comment]
Hey @MKHokinson, thanks for the tip! You saved my VSCode (and some long debugging time 😄).
The issue was definitely the notifications being disabled.

**Comment by alexgille** [comment]
Sorry for the late answer @Sertion, indeed my `git blame` was printing the right details with the right syntax.
I would have looked into the extension with the debugger but it would have taken me long time to understand the situation 😅.
Now the issue is fixed and people have an official solution for it.
