### ISSUE TITLE
Feat Request: Custmizable delay before activating blame

### ISSUE THREAD

**Issue by aaravind100** [Sertion/vscode-gitblame#139]
Could we have an option to set a delay before the blame is activated?

Use case: Having enabled inline blame, when sifting through code, the inline blame often lags behind the cursor, This can be jarring as the inline blame is not a subtle color. I can post a video later.

Having a delay can sorta mitigate this, like the cursor has to stay on a line for several 100 ms before the blame would get activated.

**Comment by Sertion** [comment]
Hey Ajith! Thank you for the feature request.

I think I understand the issue. I currently don't have a lot of time to spend on the extension but I do accept pull requests if you (or anybody else) want to make an attempt at building it.

**Comment by aaravind100** [comment]
Hey Albin, I understand.

TS/JS is not my speciality, but I'll try to give it a go :D

**Comment by aaravind100** [comment]
@Sertion i got some time to look into the code and test some things. Initial thought was just to wait for few ms and display the line blame. This sorta works partially, but when zipping around, you see a trail of the past blames and this makes it even worse than before 🙃

After thinking it through, a better solution would be have an event handler which captures cursor events (up/down cursor movements) and events which remain unchanged for x ms would triggers the line blame.

Now that i think about it, this is much more complex than adding a delay and may not be worth adding for a minor annoyance.

Do you have something else in mind or maybe give me some pointers?

**Comment by Sertion** [comment]
@aaravind100 Thanks a lot for having a look.

The entire extension is sort of build around the idea that everything happens "eventually". Perhaps something can be [done similar to how the statusbar element](https://github.com/Sertion/vscode-gitblame/blob/9a3d6c3bd9e92fd0bdfa6000302c9b6c2aed5ddc/src/git/extension.ts#L155) is updated and super short Promise.race?

**Comment by aaravind100** [comment]
> @aaravind100 Thanks a lot for having a look.
> 
> The entire extension is sort of build around the idea that everything happens "eventually". Perhaps something can be [done similar to how the statusbar element](https://github.com/Sertion/vscode-gitblame/blob/9a3d6c3bd9e92fd0bdfa6000302c9b6c2aed5ddc/src/git/extension.ts#L155) is updated and super short Promise.race?

@Sertion adding a delay in this method kinda a solves the problem.

Before:
[Before](https://user-images.githubusercontent.com/98406957/230660283-0f7e2a2c-41a1-498f-a858-c314d0191607.webm)

After adding 200ms delay:
[After](https://user-images.githubusercontent.com/98406957/230660334-9576a14d-1877-460f-8529-f3d418e0875e.webm)

Would you like me to create a pr for this?

**Comment by Sertion** [comment]
Impressive! Please do!

**Comment by aaravind100** [comment]
@Sertion i've created this (#141) pr

**Comment by Sertion** [comment]
Merged.

**Comment by Sertion** [comment]
A new version has been released. It sometimes can take a few hours before it is available for everyone.

Thank you for your time and effort!

**Comment by aaravind100** [comment]
Thanks a lot!!
