### ISSUE TITLE
Information is no longer displayed in the toolbar

### ISSUE THREAD

**Issue by mviens** [Sertion/vscode-gitblame#14]
This extension used to work wonderfully. I had to stop working on a project for a few weeks. When I come back, I no longer see any information. I uninstalled and reinstalled the extension.  I also tried switching to other Git branches.  Nothing is displayed.  

I am happy to help troubleshoot what is happening, but I don't know where to start looking.

![gitblame](https://cloud.githubusercontent.com/assets/8459232/26130429/78ea4ba8-3a49-11e7-93af-f80bf15c1145.png)

**Comment by Sertion** [comment]
Hey Mike. I really hope we can find out what the problem is together.

A few follow up questions:

* Is your Vscode `git.path` setting configured to a working `git` binary or `null`?
* Do you have errors if you open up `Output` and select `gitblame` from [the dropdown](http://i.imgur.com/DMu0bVW.png)?
* Do you get proper output from git when doing a `git blame <filename>`?
* What version of git do you use?
* What operating system?

**Comment by mviens** [comment]
- Is your Vscode git.path setting configured to a working git binary or
   null?

"git.path": "C:\\Dev\\Git\\bin"

This is the correct location where Git is installed.


   - Do you have errors if you open up Output and select gitblame from the
   dropdown <http://i.imgur.com/DMu0bVW.png>?

There are indeed errors here:


Error: spawn C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError:
spawn C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError: spawn
C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError: spawn
C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError: spawn
C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError: spawn
C:\Dev\Git\bin ENOENTError: spawn C:\Dev\Git\bin ENOENTError: spawn
C:\Dev\Git\bin ENOENT


   - Do you get proper output from git when doing a git blame <filename>?

Yes.


   - What version of git do you use?

>git --version

git version 2.13.0.windows.1


   - What operating system?

Windows Server 2012 R2


Even though you did not ask, this is the version of VSC I am using
(according to the Help | About screen in VSC):

Version 1.12.2
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0



---
Mike V.

**Comment by Sertion** [comment]
Thank you for the information!

Does it work if you change `C:\\Dev\\Git\\bin` `C:\\Dev\\Git\\bin\\git.exe`?

**Comment by mviens** [comment]
It does indeed work when I change that.  Thank you very much for your
prompt replies and help with getting this resolved.


---
Mike V.
