### ISSUE TITLE
Show multiple blame for all lines selected

### ISSUE THREAD

**Issue by babaric-dev** [Sertion/vscode-gitblame#140]
If more than one line of code is selected / multi cursor, blame all lines chosen.

**Comment by Sertion** [comment]
Hey. Thanks for the feature request.

I think this is a feature that [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) has. I am not interested in adding support for that.

**Comment by babaric-dev** [comment]
I don't want to use GitLens. it is too robust and I don't need all features there.
