### ISSUE TITLE
Inline message drawn on top of code when backspacing from EOL

### ISSUE THREAD

**Issue by kgalford1** [Sertion/vscode-gitblame#142]
# Versions
vscode `v1.78.1` with all extensions disabled except for Git Blame `v10.2.0`. Bug appears to be introduced with inline blame string in `v10.0.0`.

![image](https://github.com/Sertion/vscode-gitblame/assets/6301097/19629acc-a46d-4d1e-b633-f59216c849f6)

![image](https://github.com/Sertion/vscode-gitblame/assets/6301097/e6f41fc8-fe01-42f8-aeb6-82ec7021c306)

# Example
Cursor at EOL 82.
![image](https://github.com/Sertion/vscode-gitblame/assets/6301097/cf4caaa9-1d56-40a4-bc12-48d652249e3b)

Backspacing the `\n` on 82.
![image](https://github.com/Sertion/vscode-gitblame/assets/6301097/e4aba2b7-b375-4013-94da-ba5e95b04893)

Continuing to backspace and the `+ 45` is drawn underneath the inline message.
![image](https://github.com/Sertion/vscode-gitblame/assets/6301097/c1a89595-8883-47af-af0e-e4eac39b0a60)

**Comment by Sertion** [comment]
Hey Kim. Thanks for the detailed bug report!

I did not implement the line decorator feature and do not know how it works but perhaps I'll have some time to look into this in the near future.

**Comment by kgalford1** [comment]
No worries - I have virtually no experience with extension dev, but perhaps may look into this as well.

Loving the extension - with this fix it's all the blame functionality from GitLens I need :smile:

**Comment by Sertion** [comment]
I had some time and I think I got it working. Will spend some more time looking into a fix for #144 before releasing a new version.

**Comment by stevemandl** [comment]
This might be the same issue, so I thought you would want to test this case too before deploying a fix.
It also happens when deleting a newline on a blank line: 
![image](https://github.com/Sertion/vscode-gitblame/assets/5465626/4d3c6078-22cd-4667-aa40-4f8976c1ffcb)
and after hitting the delete key:
![image](https://github.com/Sertion/vscode-gitblame/assets/5465626/67fe7637-5f51-4521-a43a-d86a08afd097)
I'm running v10.2.0 on WSL: Ubuntu

**Comment by thijsputman** [comment]
A (sort of) workaround is to configure the following:

```json
"gitblame.inlineMessageNoCommit": ""
```

This blanks out the blame-message on modified lines – (mostly) preventing the issue from occurring in the first place.

Might this be a sensible configuration option to introduce? Omitting the message on modified lines provides effectively the same information as showing "Not Commited Yet"...

**Comment by Sertion** [comment]
A new version that fixes this issue has been pushed to the marketplace. It can sometimes take a few hours for it to be available for everyone. I will close this issue for now. Please comment if the issue persists after upgrading to version 10.2.1 or later.
