### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nagendra-pujari** [Sertion/vscode-gitblame#143]
- Issue Type: `Performance`
- Extension Name: `gitblame`
- Extension Version: `10.2.0`
- OS Version: `Linux x64 5.4.0-109-generic`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/waderyan.gitblame-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Sertion** [comment]
Hey nagendra-pujari!

I need the file referred to in the comment in order to do anything with this report. Please attach it if you want any action on this.
