### ISSUE TITLE
"Will not blame X, Outside the current workspace."

### ISSUE THREAD

**Issue by YaroST12** [Sertion/vscode-gitblame#148]
Hello there,

Due to an annoying bug related to git gutters in vscode (https://github.com/microsoft/vscode/issues/176497) I have to use a workaround, which sets --git-dir argument to the actual directory of the .git folder...

... which causes git blame to think that all files are outside its current workspace.
The workaround in question can be found here: https://stackoverflow.com/questions/75615136/vscode-vscodium-showing-git-gutters-even-though-there-are-no-actual-changes-in-t

Is there anything I can modify in the workaround script or in the extention itself to make them work well together? Thanks.

**Comment by YaroST12** [comment]
I've updated my script to work nicely with both vscode and git blame extension, but I may have an idea as to why this extension started misbehaving:
perhaps it makes more sense to parse --work-tree here instead of --git-dir: https://github.com/Sertion/vscode-gitblame/blob/main/src/git/util/gitcommand.ts#L71-L72

**Comment by Sertion** [comment]
General Furman.

I am not exactly sure what I can do here.

I've found some places in the extension where we assume that the git path and the file path has overlap and I'm working on changing them to be more generic. Other than that the modified script looks like it should work. The [extension uses](https://github.com/Sertion/vscode-gitblame/blob/64412646e29995f49be35a2e91011128ea77b1b3/src/git/util/gitcommand.ts#L14) the [vscode.git built-in extension](https://github.com/microsoft/vscode/tree/main/extensions/git) to get [the path to the git executable](https://github.com/microsoft/vscode/blob/main/extensions/git/src/git.ts#L145) ([permanent link](https://github.com/microsoft/vscode/blob/f448922d9b48633388c1761146ddc9b7e8d5f79b/extensions/git/src/git.ts#L145C6-L145C6)).

Perhaps this was the issue you where running into?

**Comment by YaroST12** [comment]
Hi, the modified script works. Waiting for VSCode to get fixed :(
