### ISSUE TITLE
Feature Request - Right Justified Inline Blame Messages.

### ISSUE THREAD

**Issue by gpaulsen** [Sertion/vscode-gitblame#149]
Feature Request:

  It would be really great to be able to enable right justification of inline git blame messages.
  
  I would assume this would be a new boolean setting that would change the location of the inline git blame message to line up across the right hand side of the vscode editor (honoring the other `gitblame.inlineMessage` settings as well).  There would need to be some priority so that the code would always render "on top" of the blame messages for really long lines.
  
  I have no idea how the vscode renderer works (or if it works with languages that read right to left), but I'd hope that a change like this would not be too difficult.
  
  Thanks for considering this feature request, and for the already excellent extension.

**Comment by Sertion** [comment]
Hey Geoff! Thanks for the feature request.

Sadly [TextEditor.setDecorations](https://code.visualstudio.com/api/references/vscode-api#TextEditor.setDecorations) is very limited in [what styling it supports](https://code.visualstudio.com/api/references/vscode-api#ThemableDecorationAttachmentRenderOptions).

If this changes in the future we can definitely reconsider adding this as an option.
