### ISSUE TITLE
Fix "Terminal" view of blame for Windows CMD?

### ISSUE THREAD

**Issue by shunf4** [Sertion/vscode-gitblame#150]
Currently clicking "Terminal" button, the command line sent to the terminal is in UNIX shell syntax `git show 4e3cfa8cd49f315b0178577bd9f45ae0f1f85342; exit`, which doesn't work if my default terminal profile is CMD.

**Comment by Sertion** [comment]
Hello Shun Zi! Thanks for the report.

I'll see what I can do.

**Comment by Sertion** [comment]
I am not able to detect what specific shell is being used by the createTerminal function. I've added a section to the readme about this as a known issue.
