### ISSUE TITLE
Request to update marketplace version

### ISSUE THREAD

**Issue by cell2749** [Sertion/vscode-gitblame#152]
I was hoping to get inline blame with the latest configuration options that supports inline blaming.

At the moment adding these lines to the vscode settings JSON does nothing for me:
<img width="404" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/6397761/70f66ed0-2b93-46c9-b457-d01cf93ab328">

I am not sure if I am doing something wrong. These are all the versions available for me via the Extensions menu in the vscode:
<img width="172" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/6397761/95a4c1f1-75ca-4107-955e-a152643fe0df">

**Comment by Sertion** [comment]
Hey Nikita. What marketplace?

Officially the extension is only available from the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame) and the [Open VSX Registry](https://open-vsx.org/extension/waderyan/gitblame). Please be careful if you download it from anywhere else.

The extension also requires specific versions of VSCode. It could be that you are not running the latest version of the editor.

**Comment by cell2749** [comment]
Yes, I was using Visual Studio Marketplace.

It looks like when I go into VScode extensions the version shows as 10.5.0 but when I hit install -> it installs 9.0.1:

Before install:
<img width="341" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/6397761/283fac6e-2545-4e5b-bb89-ece9eef64df2">
After install:
<img width="352" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/6397761/c5f17aee-9895-42fb-8648-c3983a675b46">
And same list of versions is shown as above.

I am on MAC, I wonder if there is problem with compatibility. If not then I think this can be closed since the problem is most probably on my end

**Comment by Sertion** [comment]
It looks like there is a cached version of the extension somewhere on your machine. The [only limit the extension sets](https://github.com/Sertion/vscode-gitblame/blob/0c336aa618b11d663ce9ce2465c9350658479ec2/package.json#L7) is what vscode API version it can support.
