### ISSUE TITLE
Shows old author name (username)

### ISSUE THREAD

**Issue by EstesE** [Sertion/vscode-gitblame#158]
I changed my github username over a year ago and new projects still show my old username.

**Comment by Sertion** [comment]
Hey Eric.

If you are referring to a link in [CHANGELOG.md](https://github.com/Sertion/vscode-gitblame/blob/main/CHANGELOG.md) please create a pull request changing from what it used to be to whatever it is now.

If you are referring to the name field that is connected to the git commits on your machine this extension only reads the output from `git blame`.
