### ISSUE TITLE
First name only?

### ISSUE THREAD

**Issue by ipkpjersi** [Sertion/vscode-gitblame#159]
Hi,

I might be mistaken but I seem to be having trouble getting it to display the author's first name only, is this not possible?

Cheers.

**Comment by Sertion** [comment]
Hey ipkpjersi!

The "author" (or "committer") in git is stored as two strings and often printed as [`%an <%ae>`](https://www.git-scm.com/docs/git-log#Documentation/git-log.txt-emanem). [I do not want to](https://github.com/kdeldycke/awesome-falsehood#human-identity) do any [_parsing_ or modifications](https://github.com/kdeldycke/awesome-falsehood#emails) of that information.

Therefore it is not possible to print only part of a name.
