### ISSUE TITLE
Plural string for 1 of thing (e.g. "1 months")

### ISSUE THREAD

**Issue by adambowles** [Sertion/vscode-gitblame#16]
Example can be seen in your [example gif](https://raw.githubusercontent.com/Sertion/vscode-gitblame/0b0999977c4b91cc052ad3fa304c7bc4eba2de2a/images/GitBlamePreview.gif)

**Comment by adambowles** [comment]
I recommend using [moment](http://momentjs.com/docs/#/displaying/fromnow/) to manage this for you

**Comment by Sertion** [comment]
Hey Adam, thank you for the issue and PR!

Right now there is a token for moments `timeFrom` function: `${time.from}`

I will look into fixing the plural/singular issue.

**Comment by Sertion** [comment]
I just got back home and started looking into this.

Is this still an issue or is it only an issue in the demo gif?

**Comment by adambowles** [comment]
Yeah it's currently in 1.10.0, it was just easier to use the gif to demonstrate visually

**Comment by Sertion** [comment]
But only for months, right?

Will release a new version after some further testing.

**Comment by adambowles** [comment]
Not just 'months'; you can see all time units have plurals [here](https://github.com/Sertion/vscode-gitblame/pull/17/files#diff-fa007bba8ece8914c1feac10e7896176)

**Comment by Sertion** [comment]
Thanks for being persistent here. For some reason I thought it never could render with one day or one hour.

**Comment by adambowles** [comment]
No problem 👍
