### ISSUE TITLE
`gitblame.delayBlame` triggers for each character typed

### ISSUE THREAD

**Issue by redactedscribe** [Sertion/vscode-gitblame#160]
The delay in its current state is only useful (accurate) the moment you click on a line. Once you start typing, it creates a new timer for the next X seconds, per character typed. You'll notice that the inline blame keep appearing much sooner than the delay value set.

Thanks.

v10.5.1

**Comment by Sertion** [comment]
Hey redactedscribe. Thanks for the bug report.

I'll see what I can do. Sadly it is not possible to know what type of text change or selection change the user does with the [vscode extensions API](https://code.visualstudio.com/api/references/vscode-api).

**Comment by Sertion** [comment]
I was not able to reproduce the issue but I saw some possible changes to mitigate the behavior you are describing. Attached to this post is a pre-release build. If you could test it and verify that the issue is resolve that would be very appreciated!

[gitblame-10.6.0-pre-release.zip](https://github.com/Sertion/vscode-gitblame/files/13443159/gitblame-10.6.0-pre-release.zip)

**Comment by redactedscribe** [comment]
```json
    "gitblame.inlineMessageEnabled": true,
    "gitblame.delayBlame": 3000,
```

1. Click on a line and wait 3 seconds. Blame appears.
2. Type a letter every second for 10 seconds. Notice blame appears on the line after 3 seconds, and keeps disappearing and reappearing after every letter typed even though only 1 second is passing between presses.

Blame should only appear 3 seconds after the last letter typed.

**Comment by Sertion** [comment]
Sorry for the way. A new version with the change has been pushed to the marketplaces. It should become available in the next hours/days.

Thank you for the bug report and feedback!

**Comment by redactedscribe** [comment]
And thank you for the fix!
