### ISSUE TITLE
Alternate ssh profile breaks remote URL for nonstandard origins

### ISSUE THREAD

**Issue by petervandivier** [Sertion/vscode-gitblame#161]
My `.ssh/config` is set up as below...

```
Host github.com
    Hostname github.com
    User git
    IdentityFile ~/.ssh/personal.id_ed25519

Host work
    Hostname github.com
    User git
    IdentityFile ~/.ssh/work.id_ed25519
```

...when I'm in a work repository and click through to the "Online" blame, the string `github.com/` is replaced with `work`. e.g. `https://github.com/microsoft/PowerShellForGitHub/commit/deadbeef` becomes `https://workmicrosoft/PowerShellForGitHub/commit/deadbeef`

<img width="393" alt="git remote -v shows nonstandard origin" src="https://github.com/Sertion/vscode-gitblame/assets/10898767/5d5b1b78-a944-421d-bf3c-6157fe9444f3">

<img width="649" alt="opening the blame online" src="https://github.com/Sertion/vscode-gitblame/assets/10898767/759cf4db-0644-4f2b-9c4d-42cf98fcece0">

<img width="417" alt="vscode URL launcher showing malformed URL" src="https://github.com/Sertion/vscode-gitblame/assets/10898767/f4bb6a93-d19a-4279-884f-97370d6d6fca">

I can work around this by copying the URL from the dialogue (as seen in the screencap above) and manually editing it (thanks #47 😄 (I think)), but it would be nice if this could be detected automagically. 

<sub>(Apologies if this has been addressed by a previous issue. I wasn't able to parse out if that was the case from a quick browse)</sub>

**Comment by Sertion** [comment]
Hey Peter Vandivier. Thanks for the feature request. I have a follow up question:

Would it work if the generated URL was `https://work/microsoft/PowerShellForGitHub/commit/deadbeef` (a slash between `work` and `microsoft` in the former hostname?

Other than that I don't see a way where the extension could be aware of this. If git isn't aware, the extension isn't either.

**Comment by petervandivier** [comment]
> Would it work if the generated URL was ... a slash between [the origin] and [the organization]?

For me this would not work. `work` as an entity is just defined in my ssh config and not in my hosts file or anywhere that my browser would pick it up.

Tbh I was trying to think of other workarounds for a little bit before submitting the ticket but I couldn't come up with anything quickly (or at least nothing sensible). If I do think of something other than the current workaround I'll be sure to update this thread :slightly_smiling_face:

**Comment by Sertion** [comment]
Non-standard setups usually has their ups and down. I will close this as out of scope.

I have very (__very__) limited experience with them, but there are [conditionals available for the git configuration](https://git-scm.com/docs/git-config#_conditional_includes). Perhaps you can tell it to [use different SSH-keys](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand) based on what parent folder the git-repo resides in?

Good luck and thanks for taking the time to create a ticket even if it did not lead to a fix for your issue!

**Comment by petervandivier** [comment]
Fair enough 🙂 

I figured it was worth documenting the behaviour even if there's nothing to be done.

> Perhaps you can tell it to use different SSH-keys based on what parent folder the git-repo resides in?

That's actually [exactly what I do](https://stackoverflow.com/q/57275547/4709762) with my current setup. The alt ssh profile facilitates that in part.

Thanks in any case for your work on this lovely extension! 😄

**Comment by petervandivier** [comment]
Fair enough 🙂 

I figured it was worth documenting the behaviour even if there's nothing to be done.

> Perhaps you can tell it to use different SSH-keys based on what parent folder the git-repo resides in?

That's actually [exactly what I do](https://stackoverflow.com/q/57275547/4709762) with my current setup. The alt ssh profile facilitates that in part.

Thanks in any case for your work on this lovely extension! 😄
