### ISSUE TITLE
Bonobo Git Server uses UUID for repository IDs

### ISSUE THREAD

**Issue by Daviid-P** [Sertion/vscode-gitblame#167]
Bonobo Git Server uses UUID to identify repositories.

My remote origin is like this

```
[remote "origin"]
        url = http://david@192.168.1.89/Bonobo.Git.Server/MyRepository.git
```

`${tool.protocol}//${gitorigin.hostname}${gitorigin.port}${gitorigin.path}${tool.commitpath}${hash}`

And the webview commit url looks like this:
`http://git.local/Bonobo.Git.Server/Repository/Commit/13a15c5a-b4e1-407c-a011-f4f34ac74747?commit=6d6582febf4f01e5fe22021b3d2bfe616a1bbdb5`

This is what the extension generates by default.
`http://git.local/Bonobo.Git.Server/MyRepository/commit/6d6582febf4f01e5fe22021b3d2bfe616a1bbdb5`

Is there a way to translate MyRepository to the correct UUID that Bonobo uses?

Something like

```
"translations": {
    "MyRepository": "13a15c5a-b4e1-407c-a011-f4f34ac74747",
    "MyRepository2": "98267044-947d-4bf5-9893-7d0a290255da",
    "MyRepository3": "30da658f-94f7-4b7d-867f-6acf974e43f3",
  },
```

Thanks.

**Comment by Sertion** [comment]
Hey David! Thanks for the feature request.

I am not a big fan of adding features for singular services. The solution you propose looks a lot like having [a workspace setting](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings) for each repository. It can even be committed with the code allowing many users to share the URL with the UUID "baked" in.

Would that be a workable solution?

**Comment by Daviid-P** [comment]
Yeah, that´d be enough.
