### ISSUE TITLE
Define a custom theme color for the inline message

### ISSUE THREAD

**Issue by jrieken** [Sertion/vscode-gitblame#168]
Today, the inline messages uses `editorCodeLens.foreground`. This is a good default but I would like to tweak the colour independent of code lens. I suggest to introduce a new extension specific theme color that defaults to `editorCodeLens.foreground` but allows to be customized. This can be done like https://code.visualstudio.com/api/references/contribution-points#contributes.colors and I am also happy to contribute a PR if desired.

**Comment by Sertion** [comment]
Hey Johannes! Thank you for the feature request.

I did not know about the `contributes.color` contribution point. It solves the issue I've had with similar requests earlier.

I'll see if I can implement it today.

**Comment by Sertion** [comment]
A new version has been released.
