### ISSUE TITLE
Feature Request: Copy commit hash on info message click

### ISSUE THREAD

**Issue by harshbhatt** [Sertion/vscode-gitblame#171]
Thanks for the awesome extension! Have a small feature request - either another button or simply copy the commit has on message click.

**Comment by Sertion** [comment]
Hey Harsh! Thanks for the feature request.

It is currently possible to copy the hash to clipboard using the "Git Blame: Copy hash to clipboard"-command but adding an option to the status bar click event should be pretty straight forward. I am not a fan of adding it as an option to the dialog as two buttons already feels a lot for what the extension does.

**Comment by Sertion** [comment]
I've added the "Copy hash to clipboard" option to `gitblame.statusBarMessageClickAction`. When set to this clicking the status bar element will copy the the hash to the clipboard.

The new version has been uploaded to to the stores.
