### ISSUE TITLE
No longer works since 11.0.0

### ISSUE THREAD

**Issue by MartijnHols** [Sertion/vscode-gitblame#174]
Thanks for the extension! It's exactly what I want. Unfortunately since 11.0.0, the blame is no longer working with the message "No info about the current line":

<img width="316" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/4565223/5e585722-3743-4481-bebd-b01433b42447">

All commands also fail. This is in a file with 41 lines, and changing the `gitblame.maxLineCount` setting seem to make no difference. The extension works fine after downgrading to 10.11.0.

**Comment by Sertion** [comment]
Hey Martijn. Thank you for the bug report!

I know it is unhelpful but: "it works on my machine(s)".

Do the commands fail silently or with an error message?

What version of vscode, git, and operating system do you use? Does the "Git Blame" output log contain anything?

**Comment by Sertion** [comment]
That repository works for me as well. I've done some digging and made some changes. I would appreciate it a lot if this pre-release(?) version could be tested:

[gitblame-11.0.1.zip](https://github.com/Sertion/vscode-gitblame/files/15473580/gitblame-11.0.1.zip)

**Comment by MartijnHols** [comment]
No difference

**Comment by amc6** [comment]
I'm also having a similar issue, with slightly different UI. 
<img width="235" alt="image" src="https://github.com/Sertion/vscode-gitblame/assets/1111584/96c0802f-3607-4422-ac70-c8a919bae0e8">

Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

git:  2.45.0
OSX 14.5 (23F79)


I can't figure out much of a pattern yet. It doesn't occur on every line of the file. The time seems to be from when I opened the file in vscode, not when changes were last made to the file. Also seems to be uncorrelated with commit author. Even a given commit is sometimes shows correctly in the blame and sometimes not.

Manually running `git blame` or `git blame -C` on the file seems to produce the expected results. It seems from logs that this extension uses `git blame -C --incremental`. I'm not familiar with `--incremental` but from what I can tell it is also outputting the right data. 

I had a theory that the bug occurred when the lines output from `--incremental` were out of order, but that doesn't seem to be the case once I tested enough.

Here's some of the recent output from the git blame extension:
```
2024-05-28 14:32:58.194 [info] /opt/homebrew/bin/git blame -C --incremental -- /Users/adam/code/monorepo/server/__tests__/modules/factoring/onboarding/factoring-onboarding-service.test.ts
2024-05-28 14:32:58.813 [info] Blamed "/Users/adam/code/monorepo/server/__tests__/modules/factoring/onboarding/factoring-onboarding-service.test.ts"
2024-05-28 14:34:10.991 [info] /opt/homebrew/bin/git ls-remote --get-url origin
2024-05-28 14:34:10.999 [info] /opt/homebrew/bin/git symbolic-ref -q --short HEAD
2024-05-28 14:34:11.006 [info] /opt/homebrew/bin/git config branch.adam/link_carrier_to_org_earlier.remote
2024-05-28 14:34:11.014 [info] /opt/homebrew/bin/git config remote.origin.url
2024-05-28 14:34:11.021 [info] /opt/homebrew/bin/git ls-files --full-name -- /Users/adam/code/monorepo/server/__tests__/modules/factoring/onboarding/factoring-onboarding-service.test.ts
2024-05-28 14:34:11.028 [info] /opt/homebrew/bin/git rev-parse --abbrev-ref origin/HEAD
2024-05-28 14:34:11.704 [info] /opt/homebrew/bin/git ls-remote --get-url origin
2024-05-28 14:34:11.713 [info] /opt/homebrew/bin/git symbolic-ref -q --short HEAD
2024-05-28 14:34:11.719 [info] /opt/homebrew/bin/git config branch.adam/link_carrier_to_org_earlier.remote
2024-05-28 14:34:11.726 [info] /opt/homebrew/bin/git config remote.origin.url
2024-05-28 14:34:11.733 [info] /opt/homebrew/bin/git ls-files --full-name -- /Users/adam/code/monorepo/server/__tests__/modules/factoring/onboarding/factoring-onboarding-service.test.ts
2024-05-28 14:34:11.740 [info] /opt/homebrew/bin/git rev-parse --abbrev-ref origin/HEAD
2024-05-28 14:37:00.152 [info] /opt/homebrew/bin/git ls-remote --get-url origin
2024-05-28 14:37:00.164 [info] /opt/homebrew/bin/git symbolic-ref -q --short HEAD
2024-05-28 14:37:00.170 [info] /opt/homebrew/bin/git config branch.adam/link_carrier_to_org_earlier.remote
2024-05-28 14:37:00.176 [info] /opt/homebrew/bin/git config remote.origin.url
2024-05-28 14:37:00.183 [info] /opt/homebrew/bin/git ls-files --full-name -- /Users/adam/code/monorepo/server/__tests__/modules/factoring/onboarding/factoring-onboarding-service.test.ts
2024-05-28 14:37:00.189 [info] /opt/homebrew/bin/git rev-parse --abbrev-ref origin/HEAD
```

**Comment by Sertion** [comment]
Hey @amc6. Thanks for the added information. Have you tried the pre-release build mentioned above? The behaviour you report is how the bug I found in that one could have shown itself.

**Comment by alexneo2003** [comment]
Have same issue with Git Blame v11.0.0
Git Blame v10.11.0 - work well

Output log for Git Blame
<img width="1192" alt="Monosnap 2024-05-29 13-41-51" src="https://github.com/Sertion/vscode-gitblame/assets/11705902/663c2487-29c7-4054-aa0b-151b986be2c1">

My `/usr/local/git/etc/gitconfig` file 
<img width="839" alt="Monosnap gitconfig — etc 2024-05-29 13-43-41" src="https://github.com/Sertion/vscode-gitblame/assets/11705902/18026364-2a75-4e39-8745-7281bd7cf7b9">

**Comment by Sertion** [comment]
Hey @alexneo2003. Thanks for the addition!

A few questions:
* Can you run `git rev-parse --absolute-git-dir` in your terminal outside of vscode?
* Have you edited this file or is it the default content?
* Are you on a Mac?

**Comment by alexneo2003** [comment]
> Hey @alexneo2003. Thanks for the addition!
> 
> A few questions:
> 
> * Can you run `git rev-parse --absolute-git-dir` in your terminal outside of vscode?
> * Have you edited this file or is it the default content?
> * Are you on a Mac?

1. `fatal: Not a git repository (or any of the parent directories): .git`
2. yes, I have edited that file (for no one file that I have edited blame not working)
3. yes, Mac

**Comment by Sertion** [comment]
> > Hey @alexneo2003. Thanks for the addition!
> > A few questions:
> > 
> > * Can you run `git rev-parse --absolute-git-dir` in your terminal outside of vscode?
> > * Have you edited this file or is it the default content?
> > * Are you on a Mac?
> 
>     1. `fatal: Not a git repository (or any of the parent directories): .git`
> 
>     2. yes, I have edited that file (for no one file that I have edited blame not working)
> 
>     3. yes, Mac

Thank you for the quick response. I was unclear. Could you please run `git rev-parse --absolute-git-dir` in a folder with a git repository and have you edited `/usr/local/git/etc/gitconfig`?

**Comment by alexneo2003** [comment]
> Thank you for the quick response. I was unclear. Could you please run `git rev-parse --absolute-git-dir` in a folder with a git repository and have you edited `/usr/local/git/etc/gitconfig`?

1. /Users/*username*/Documents/projects/*project-name*/.git
2. by myself - no

**Comment by Sertion** [comment]
> > Thank you for the quick response. I was unclear. Could you please run `git rev-parse --absolute-git-dir` in a folder with a git repository and have you edited `/usr/local/git/etc/gitconfig`?
> 
>     1. `/Users/*username*/Documents/projects/*project-name*/.git`
> 
>     2. by myself - no

What does `type git` print in the same folder as you ran `git rev-parse --absolute-git-dir`?

**Comment by alexneo2003** [comment]
> What does `type git` (or `which git` if macs don't have `type`) print in the same folder as you ran `git rev-parse --absolute-git-dir`?

`git is /usr/local/bin/git`

**Comment by Sertion** [comment]
Thanks to the information provided I think I've found a second issue with the changes made in 11.0.0. Attached is a pre-release build. I would love it if someone who has the issue could try it and report back!

[gitblame-11.0.1-pre-release-2.zip](https://github.com/Sertion/vscode-gitblame/files/15487801/gitblame-11.0.1-pre-release-2.zip)

**Comment by alexneo2003** [comment]
> Thanks to the information provided I think I've found a second issue with the changes made in 11.0.0. Attached is a pre-release build. I would love it if someone who has the issue could try it and report back!
> 
> [gitblame-11.0.1-pre-release-2.zip](https://github.com/Sertion/vscode-gitblame/files/15487801/gitblame-11.0.1-pre-release-2.zip)

I have checked it and it works well

**Comment by Sertion** [comment]
Thank you! 11.0.1-pre-release-2 has been linted, packaged and uploaded to the marketplace. I hope this will solve the issue for everyone in this thread (and those affected who has not participated)!

If issues still remain please open a new bug report. Thanks everyone for your patience and help!

**Comment by MartijnHols** [comment]
Thanks for helping us! It's much appreciated (as well as the extension in the first place).

For anyone still running into the issue: I don't know if something was weird on my end, but I had to uninstall and reinstall the extension in order to get the update you pushed to fix the issue. No amount of extension restart and window reloading (via the command palette) applied the fix. Maybe restarting VSCode would have worked as well.
