### ISSUE TITLE
Extension isn't working

### ISSUE THREAD

**Issue by DonaldDuck313** [Sertion/vscode-gitblame#177]
I keep seeing this where the git blame output is supposed to be:

![image](https://github.com/user-attachments/assets/35b38089-e39c-4529-bd0d-fafe92567fc7)

If I go to Extensions > Git Blame > Features > Runtime Status, it shows these errors:

```
Runtime Status
Activation
Activated by onStartupFinished event: 4ms

Uncaught Errors (8)
 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/.git/HEAD'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/interface.hpp'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/cache.cpp'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/.git/HEAD'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/interface.cpp'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/.git/HEAD'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/api.cpp'

 ENOSPC: System limit for number of file watchers reached, watch '/home/myname/Documents/repo/.git/HEAD'
```

**Comment by Sertion** [comment]
Hello DonaldDuck313. Thanks for the bug report.

Is this an occasional issue or something that happens every time you start vscode? What do you get when you run [`lsof | grep inotify | wc -l`](https://stackoverflow.com/a/24994331/1421887) in a terminal?

**Comment by DonaldDuck313** [comment]
> Is this an occasional issue or something that happens every time you start vscode?

It's occasional in the sense that it doesn't happen all the time, but if it happens once, then it happens again for all new files that I open, and restarting vscode doesn't help. I'm not sure what causes it to start happening, it seems to be random.

> What do you get when you run [`lsof | grep inotify | wc -l`](https://stackoverflow.com/a/24994331/1421887) in a terminal?

I get this:

```
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.
5130
```

It prints the warning immediately, then hangs for a few seconds, then prints the number and exits (it's a different number each time but is usually a 4-digit number starting with 51).

**Comment by DonaldDuck313** [comment]
It seems to be possible to solve this issue by setting the max number of file watchers to 1000000000 by using the method explained here: https://stackoverflow.com/a/55411444/4284627
