### ISSUE TITLE
Blame doesn't show up for specific files in the status bar but appears inline

### ISSUE THREAD

**Issue by sriranggd** [Sertion/vscode-gitblame#178]
Thank you for this extension. It's very helpful.

This extension largely works for me. Sometimes the blame doesn't appear for a specific file(s) in the status bar. At the same time it appears for other files.  I prefer the `status bar` display than the inline display and have always kept the inline display disabled.

When I check the output of the extension and I see that `git blame` is actually called on the file for which the blame doesn't appear on status bar. So I thought that the extension is failing to parse the output of `git blame` for some files.

But then today, I tried enabling the inline display and it shows up even for the file for which blame doesn't appear in the status bar.

I would really appreciate if I can get any help to make `git blame` show up in the status bar for all the files. Inline is too distracting for me.

Here are the system / software details (From "About" of VS Code) : 

```
VS Code Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0

Git Blame Extension Version :  v11.0.1
```

Please let me know if any other information is needed.

**Comment by Sertion** [comment]
Hey Srirang! Thank you for the bug report.

I am not able to recreate the issue you are describing in any of my test repositories. Do the files have anything in common? Do they have many lines? Do they have uncommitted changes? Is the inline git information correct for the line it is showing next to or are they misaligned?

Attached is a pre-release version of what I've been working on for 11.0.2. It contains a lot more debug messages for the log. Among other it logs when the blame process gets data and when the status bar updates. To see the new messages you need to change the log level for the output view to _Debug_ (or _Trace_ if you want _all_ the messages).

[gitblame-11.0.2.zip](https://github.com/user-attachments/files/16734323/gitblame-11.0.2.zip)

**Comment by sriranggd** [comment]
Hi @Sertion, thanks for the quick response.

The debug logs from the 11.0.2 version you shared helped me figure it out. It was because of lack of space in the status bar that caused the issue. Whenever I was not seeing anything in the status bar, it was because the name of the committer was too long to fit in the space available in the status bar.

Further I had an AWS profile with a long name that was occupying lot of space. When I switched to a profile named `default`, all the blame info started appearing for all the files / lines (with where the committer name was long).

Sorry for the false alarm and once again, thank you for your help. I will close this issue now.

As a follow up, see if it would make sense to show clipped info with ellipsis on the status bar when enough space is not available (if that is detectable) instead of not showing anything at all. I have a feeling that it is VS-Code which decides whether to show something or not on the status bar. So I suppose an extension can just try to show only info that will fit the available space.

**Comment by Sertion** [comment]
Glad the issue was resolved!

> As a follow up, see if it would make sense to show clipped info with ellipsis on the status bar when enough space is not available (if that is detectable) instead of not showing anything at all. I have a feeling that it is VS-Code which decides whether to show something or not on the status bar. So I suppose an extension can just try to show only info that will fit the available space.

Sadly there is no feedback from vscode to the extension when this happens.
