### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Tawinpas** [Sertion/vscode-gitblame#179]
- Issue Type: `Performance`
- Extension Name: `gitblame`
- Extension Version: `11.0.1`
- OS Version: `Linux x64 6.8.0-41-generic`
- VS Code version: `1.92.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/waderyan.gitblame-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Sertion** [comment]
Can't look into without the cpuprofile.
