### ISSUE TITLE
[FEATURE REQUEST] Would like to be able to customize the color of inline Message.

### ISSUE THREAD

**Issue by Syed-Wang** [Sertion/vscode-gitblame#180]
![image](https://github.com/user-attachments/assets/0e37ffab-c6c1-4264-9a86-a320baa38baa)

As shown in the figure, I want the inline message to be lighter than my comment color.

**Comment by Sertion** [comment]
Hey. You can use `gitblame.inlineMessage`.

**Comment by Syed-Wang** [comment]
> Hey. You can use `gitblame.inlineMessage`.嘿。你可以使用 `gitblame.inlineMessage`。

I'm not sure. Do you mean in the settings.json file? For example,`"gitblame.inlineMessage":“#545454"`？ This is not valid.

**Comment by Sertion** [comment]
It is a [color token name](https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme).

**Comment by Syed-Wang** [comment]
> It is a [color token name](https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme).它是一个[颜色标记名称](https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme)。

grateful! This works.
