### ISSUE TITLE
Please add Custom Author Label into configs

### ISSUE THREAD

**Issue by Antecer** [Sertion/vscode-gitblame#181]
`Gitlens` plugin replace my "author.name" to "You".
But `git blame` only shows my git name.

I think I need a new options variable (Git Blame: Custom Author Label) to substitute my own author name.
Please don't try to make it display "you" like gitlens, but add a custom label so that it can adapt to the preferences of different users.

**Comment by Sertion** [comment]
Hey Antecer! Thanks for the feature request.

I have some ideas on how this could be implemented, but I need some thought on how you would prefer how to deal with it:
* What defines "you" in this case? That `user.name` matches? That `user.email` matches? That both `user.name` _and_ `user.email` matches?
* Should `author.name` replace to the same setting value in the inline view, status bar view, [`informationMessage`](https://code.visualstudio.com/api/references/vscode-api#window.showInformationMessage), and the various URLs or only some of them?
* Should it apply to both `author.name` and `committer.name` or would that be unexpected?

**Comment by Antecer** [comment]
I think it would be a good idea to just add a new definable string to replace `${author.name}`.
Users can set their own, or keep the default `author.name`

**Comment by Sertion** [comment]
Thanks for the input!

I had a look at the Gitlens implementation and it sadly does not contain anything that can be reused here. It is only possible to have one `user.name` and `user.email` per repository so matching the email is probably what I'll do.

Will probably also apply this in all cases except URLs and for both `author.name` and `committer.name`.

**Comment by Sertion** [comment]
I've built a pre-release and I would love if you had a look to see if it works the way you expect!

I added a new setting called `gitblame.currentUserAlias`. If it is set and a commit user's email or committer's email matches `git config user.email` it will replace that `{author|committer}.name`.

[gitblame-11.1.0-prerelease.zip](https://github.com/user-attachments/files/17167653/gitblame-11.1.0-prerelease.zip)

**Comment by Antecer** [comment]
> I've built a pre-release and I would love if you had a look to see if it works the way you expect!
> 
> I added a new setting called `gitblame.currentUserAlias`. If it is set and a commit user's email or committer's email matches `git config user.email` it will replace that `{author|committer}.name`.
> 
> [gitblame-11.1.0-prerelease.zip](https://github.com/user-attachments/files/17167653/gitblame-11.1.0-prerelease.zip)

it will replace all `{author.name}`, we only need replace the `{author.name}` for me.

**Comment by Sertion** [comment]
Thank you for testing it. Sorry that it had an issue. I've corrected it.

[gitblame-11.1.0-prerelease2.zip](https://github.com/user-attachments/files/17174471/gitblame-11.1.0-prerelease2.zip)

**Comment by Antecer** [comment]
> Thank you for testing it. Sorry that it had an issue. I've corrected it.
> 
> [gitblame-11.1.0-prerelease2.zip](https://github.com/user-attachments/files/17174471/gitblame-11.1.0-prerelease2.zip)

Now, it works good!
