### ISSUE TITLE
"no info about the current line" on every line

### ISSUE THREAD

**Issue by Jongmassey** [Sertion/vscode-gitblame#183]
VS Code 1.95.3 in WSL2 Ubuntu on Windows 10. 

On every branch in every git folder, the extension appears not to work for any file. Hovering over the git blame icon in the bottom status bar shows the tooltip with the text "git blame - no info about current line"

**Comment by Sertion** [comment]
Hey Jon.

I can't do anything with the information you have provided. Please look in the extension output channel for any hints on what can be wrong.
