### ISSUE TITLE
Unable to get correct results after modifying a document.

### ISSUE THREAD

**Issue by gucong3000** [Sertion/vscode-gitblame#20]
For example, when I insert some newline characters before the last line of code, the status bar will be empty.
![blame](https://user-images.githubusercontent.com/1171691/27069201-54a78680-5046-11e7-8ec2-0c23a2c1f9eb.gif)

**Comment by gucong3000** [comment]
https://github.com/alessioalex/git-blame/issues/6

**Comment by Sertion** [comment]
Hey gucong. Thank you for the issue.

Right now we only blame the file when the user saves the file. This is partially because for larger repositories take a long time to be blamed and that it easier to keep track of what version of the file we are in progress of blaming.

**Comment by gucong3000** [comment]
The blame is still incorrect after the file is saved.

**Comment by Sertion** [comment]
This will be solved in 1.11.3 that I release in a few moments.
