### ISSUE TITLE
Display years when relevant

### ISSUE THREAD

**Issue by neerolyte** [Sertion/vscode-gitblame#21]
The average age of the code base I mostly work on is probably around 7 years (some lines up to at least 14 years).

I'd like large time spans to display years and months instead of just months, e.g `8 years and 1 month` instead of `97 months`.

**Comment by neerolyte** [comment]
Seems like all the code in `textdecorator.js` `toDateText()` might be better as just:

```javascript
    static toDateText(dateNow, dateThen) {
        return moment(dateThen).from(moment(dateNow));
    }
```

**Comment by Sertion** [comment]
Hey David! Thank you for the issue.

If you would like to use [`moment.fromNow`](https://momentjs.com/docs/#/displaying/fromnow/) you can use the `${time.from}` token in your settings.

**Comment by neerolyte** [comment]
Doh, failed to read the manual adequately.

Thanks @Sertion I'll close this off as it's trivially solvable with config.

**Comment by Sertion** [comment]
No problem. Happens to the best of us!
