### ISSUE TITLE
Doesn't work multi-root with workspace

### ISSUE THREAD

**Issue by IgorNovozhilov** [Sertion/vscode-gitblame#23]
when working with multi-root workspace the commit information is displayed only for files from the first directory from the other is not displayed.

VSCode - 1.16.0 / 1.17.0-insider
Git Blame - 2.1.0

![2017-09-08_10h52_51](https://user-images.githubusercontent.com/3082812/30201557-de6008d0-9483-11e7-86d9-3731eed8004a.png)

**Comment by Sertion** [comment]
Released with 2.2.0.
