### ISSUE TITLE
Include ${commit.linediff}

### ISSUE THREAD

**Issue by teresaejunior** [Sertion/vscode-gitblame#24]
It would be interesting if upon clicking on the status bar, the user could see a small diff of the line. Git Lens has something similar as popup over each line, but I find it very intrusive. So I believe that just a `${commit.linediff}` variable (with the possibility of placing it in a new line) would be more than enough!

**Comment by Sertion** [comment]
Hey teresaejunior!

I am not sure if I understand exactly what it should display. Could you tell me what should be returned for [this change](https://github.com/Sertion/vscode-gitblame/commit/16f256179bf4d887c3301e7283299a0088b88080#diff-71e806f782ea5f0cf8e82a2bb41e0c17) in `gitcommand.ts`?

**Comment by teresaejunior** [comment]
Taking the example from Git Lens, the variable would return the following text:

    -        ErrorHandler.getInstance().logCritical(new Error(`Can not execute "${commandPath}"`), 'The "git.path" property is not an executable');
    +        ErrorHandler.getInstance().logError(new Error(`Can not execute "${commandPath}" (your git.path property) falling back to "${GIT_COMMAND_IN_PATH}"`));

![linediff](https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/images/screenshot-line-blame-annotations-changes.png)

If that is difficult to implement, maybe a variable that just contains `- return code;` could be interesting.

**Comment by Sertion** [comment]
I have had time to do some further research here and it is not possible to have line breaks in a [`window.showInformationMessage`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.showInformationMessage).

I will not add this feature unless something changes in the future.
