### ISSUE TITLE
Configurable position in Statusbar

### ISSUE THREAD

**Issue by jvoigt** [Sertion/vscode-gitblame#25]
I would really appreciate a way to set a position for the tool in the statusbar.

**Comment by Sertion** [comment]
Hello and thank you for your request!

It is only possible to set a [priority through the API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#StatusBarItem). I could expose this number as a configurable setting but it would not guarantee a specific position.

Would that be what you are looking for?

**Comment by jvoigt** [comment]
Hey!
this would really help :)

**Comment by Sertion** [comment]
This feature was released as part of version 2.3.0
