### ISSUE TITLE
Author name not being displayed in the status bar

### ISSUE THREAD

**Issue by HCoban** [Sertion/vscode-gitblame#29]
Instead of the name of the commit author, "GitHub" is shown in the status bar.

![](https://d2ffutrenqvap3.cloudfront.net/items/0Q2S2n2U1f402a060k0x/Screen%20Shot%202018-03-27%20at%2012.05.42%20PM.png)

Running `git blame` in terminal outputs the author name correctly.

Version: 2.4.0

**Comment by Sertion** [comment]
Are you using the default settings? Is the repository publicly available? Can you reproduce the issue in a publicly available repository?

**Comment by HCoban** [comment]
Thank you for your answer.

I am using the default settings. The repository is not publicly available and after your recommendation I tested in a publicly available repository and could not reproduce. So I am closing the issue.
