### ISSUE TITLE
defaultWebPath handles plural not correctly 

### ISSUE THREAD

**Issue by HCoban** [Sertion/vscode-gitblame#30]
Shouldn't below conditional return the opposite like 
```
isPlural ? "commits" : "commit"
```

Currently it is

https://github.com/Sertion/vscode-gitblame/blob/f1a17b6ab403f47e5922a1e5b1a88aac8b7dd4cd/src/git/blame.ts#L123

If this was a mistake I can make a pull request and fix it. Thanks

**Comment by Sertion** [comment]
Nice catch.
