### ISSUE TITLE
View button on a BitBucket repo redirects to an incorrect path

### ISSUE THREAD

**Issue by juanjo23** [Sertion/vscode-gitblame#31]
Recently the view button redirects to repoaddress/**_commit_**/hash, which is an incorrect url:
the correct address should be: repoaddress/**_commits_**/hash
The problem is fixed if the isWebPathPlural configuration by default changes to true, I will  do a PR with the suggested change.

**Comment by Sertion** [comment]
Hey and thank you for the issue.

The singular form is the pattern for the vast majority of git platforms and will stay the default.
