### ISSUE TITLE
Commiter has replaced author by default

### ISSUE THREAD

**Issue by richardscarrott** [Sertion/vscode-gitblame#32]
The documentation says the authors name is rendered by default in the status bar, e.g. `"Blame ${author.name} ( ${time.ago} )"`, however with a recent update I've had to switch it to `"Blame ${committer.name} ( ${time.ago} )"` in my user settings to view the correct author name.

**Comment by Sertion** [comment]
Hey Richard! Thank you for the issue.

Is the repository where you are having this issue publicly available or can you recreate it in a publicly available repository?

**Comment by Sertion** [comment]
This has been solved in 2.4.2.
