### ISSUE TITLE
Exception UriError thrown when running "quick info" and "view online" commands

### ISSUE THREAD

**Issue by maaarghk** [Sertion/vscode-gitblame#34]
I have a repo in which running the above noted commands results in this:

<img width="470" alt="screen shot 2018-05-30 at 00 23 19" src="https://user-images.githubusercontent.com/3168648/40690622-b3354972-639f-11e8-9cbc-615a2cb07a57.png">

The output pane shows this:
`[ 00:22:05 | command ] /usr/local/bin/git ls-remote --get-url origin`
The result of which, when run in a terminal, follows the following format:
`git@git.someserver.com:user/repository`

Changing the remote to the format `ssh://git@git.someserver.com/user/repository` makes the extension work.

This relates to issue https://github.com/Microsoft/vscode/issues/38696 but that is closed. It is wrong to treat 'scp' style URIs like the format above as URIs per the rfc3986 spec, but I don't really know if this is an example of this extension misusing the vscode URI class or if there should be a pull request/issue raised on vscode to make that class recognise scp URIs.

Either way I feel like this extension should recognise the "scp-like" syntax as it is [totally valid](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_ssh_protocol) to use per the git documentation, and is also what most people will end up with usually since it's what github and others recommend when cloning by ssh:

<img width="379" alt="screen shot 2018-05-30 at 00 38 34" src="https://user-images.githubusercontent.com/3168648/40691020-dbfe21f6-63a1-11e8-9629-d2c2b06590bf.png">

**Comment by Sertion** [comment]
Hello maaarghk!

Thank you for the issue.

The way we currently find what link to give to the user [is rather crude](https://github.com/Sertion/vscode-gitblame/blob/8650a1b3a5950348882d3b34896dd700839183a4/src/git/blame.ts#L122) and you are more than welcome to create a pull request with a better version!

**Comment by SpikeShape** [comment]
I am having the same problem. I remember it being functional in the past but at some point it stopped working.
Just now I realized that it works for me when I am working with github repositories but not with those at work.

**Comment by Sertion** [comment]
Closed by #44 

Please create a new issue if the problem persists.
