### ISSUE TITLE
Incorrect Bitbucket link when viewing commit hash

### ISSUE THREAD

**Issue by ae-ou** [Sertion/vscode-gitblame#36]
When you click on the blame in the footer, and then click "view" in the pop up modal with the commit hash, the link that is opened in the browser is:

> https://bitbucket.org/{MY-PROJECT}/{MY-REPOSITORY}/commit/{COMMIT-HASH}

This link results in a 404 error. In order to resolve it, the URL needs to be "commits" instead of "commit". For example:

> https://bitbucket.org/{MY-PROJECT}/{MY-REPOSITORY}/commits/{COMMIT-HASH}

**Comment by ae-ou** [comment]
I think this issue is the result of the code in src/git/blame.ts at line 129. I can have another look if you want me to do so.

**Comment by Sertion** [comment]
Hey ae-ou.

Thank you for the issue.

Are you looking for the `gitblame.isWebPathPlural` setting?

**Comment by Sertion** [comment]
I will close this issue as the problem appears to be resolved.

**Comment by vytenis-nfq** [comment]
This setting should be active by default

**Comment by Sertion** [comment]
In my research BitBucket is the only git provider that uses the plural form. If you use Bitbucket exclusively you can make a change in [your global settings](https://code.visualstudio.com/docs/getstarted/settings).

**Comment by smisch** [comment]
> If you use Bitbucket exclusively you can make a change in your global settings.

and if I use both Bitbucket and Github reposities, this workaround will lead to one of them not using the correct commit urls. 

This problem is not resolved, as setting commitUrl to "guess" leads to an incorrect commit url for Bitbucket repositories. Feel free to set this issue to "Won't fix", if you don't want to support Bitbucket repos out of the box.

**Comment by Sertion** [comment]
@ae-ou, @vytenis-nfq, @smisch: Would a setting for a list of domains or hosts be a good compromise?

**Comment by smisch** [comment]
@Sertion If it comes with a good default, this sounds like it would be a perfect solution.

**Comment by Sertion** [comment]
I created #52 to work on this issue.

Comments are very welcome as I do not know what good defaults would contain. Right now it is "bitbucket" or "atlassian".
