### ISSUE TITLE
Bitbucket commit URL has typo

### ISSUE THREAD

**Issue by fabianrenner** [Sertion/vscode-gitblame#43]
with setting gitblame.commitUrl = "guess" it takes the following URL pattern at my bitbucket repos:
https://bitbucket.org/{repoTeam}/{repoName}/commit/{commitHash}

but it's "commits"
https://bitbucket.org/{repoTeam}/{repoName}/commits/{commitHash}

I tried to setup a custom URL but there is no variable for the repository name or team.

Would be nice to either have the "commits" fixed or these additional variables available in the commitUrl settings :)

**Comment by Sertion** [comment]
Greetings Fabian.

You are looking for the `gitblame.isWebPathPlural` setting.
