### ISSUE TITLE
Unable to open 'My Project': resource is not available.

### ISSUE THREAD

**Issue by aeisenberg** [Sertion/vscode-gitblame#45]
I am getting the following error when I try the "View last change online" command.

> Unable to open 'My Project': resource is not available.

Below is the output from my extensions view:

```
[ 19:23:18 | info ] Will not try to blame file "/extension-output-#4" as it is outside of the current workspace
[ 19:23:31 | command ] git ls-remote --get-url origin
[ 19:23:31 | info ] Clearing the file "/path/to/my/project/package.json" from the internal cache
[ 19:24:03 | command ] git ls-remote --get-url origin
```

Any ideas what is going on? I am happy to provide more information. Thanks.

**Comment by Sertion** [comment]
Hello Andrew!

Thank you for the issue and output log!

What does git output when you run `git ls-remote --get-url origin`in `/path/to/your/project`? If it starts with `ssh://git@`, `git@`, or `https://` the extension should try to open that URL using `commands.executeCommand("vscode.open", commitOriginUrl);`[1][2] beyond that it is up to Vscode to know how to parse the URL. It could be that your origin does not match the pattern of a normal URL.

Is your git repository self hosted or are you using an online service?

----
[1]: [Documentation for `commands.executeCommand`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#commands.executeCommand)
[2]: [Documentation for `vscode.open`](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands)

**Comment by aeisenberg** [comment]
Right...it isn't a normal url. We self-host and use urls like this:

    ssh://andrew@stamos:29418/MyProject

I could optionally add an different remote with a more normal looking url, but it would be read-only. Does your extension support using a custom remote?

...and...it looks like you the extension supports the `gitblame.commitUrl` command. So, let me try that.

**Comment by aeisenberg** [comment]
OK. This is working...mostly. I'm able to configure the commit URL so that it is correct for a single project.

There is still a problem, though. We are using gitweb as the viewer. Here is what a URL looks like:

    https://stamos:8080/gitweb?p=MyProject.git;a=commit;h=${hash}

Notice that the project name is part of the URL. As far as I can tell, there is no way of using a variable for the project name. Do you have any ideas?

**Comment by Sertion** [comment]
We could possibly add a new token that would be the last part of the URL (sans `.git`). Other than that I can't see where the project could come from.

Would that be helpful for Gitweb users? In this case there would be two tokens for `gitblame.commitUrl`:
* `hash` - The active line's blame commit's hash
* `project-name` - The last section of the origin url (`MyProject` from `ssh://andrew@stamos:29418/MyProject`)

I will look into building this. The port will still be weird. It is not possible to guess the port.

**Comment by aeisenberg** [comment]
I think that would work. Thanks. In my case (as I think is standard with gitweb) is that only the project name and hash changes when specifying a url.  The url looks something like this:

    https://gerrit.ganchrow.com:8080/gitweb?p=<PROJECT>.git;a=commit;h=<HASH>

So, if you provide the project and hash tokens, the correct url can be generated from the commitUrl setting.

**Comment by Sertion** [comment]
Have started on a new version in #46 and will try to find time for a new release this weekend.

**Comment by Sertion** [comment]
A new version has been released. It might take a day or two before it appears for update in your editor. Please confirm if it solves the issue.

**Comment by aeisenberg** [comment]
I will thanks very much.

**Comment by aeisenberg** [comment]
Woohoo! It works. Thanks for adding this feature.
