### ISSUE TITLE
Dot in username generates wrong repository URL

### ISSUE THREAD

**Issue by bolduz** [Sertion/vscode-gitblame#48]
Hello.  
I am using VS Code on Windows 10 64bit.  
I have a repository configured to use a remote as follows:

```
git@my-gitlab-instance-url:name.surname/repo-name.git
```

Everything was working fine until recently. However, since this morning, when clicking on the "View" button inside VS Code, i get redirected to the wrong URL.

This is what I get (notice the extra `/` between name and surname):
```
https://my-gitlab-instance-url/name/.surname/repo-name/commit/commit-hash
```

This is what I used to get until recently:
```
https://my-gitlab-instance-url/name.surname/repo-name/commit/commit-hash
```

I am unfortunately unable to pinpoint exactly when this behaviour changed, as I don't normally use the blame functionality from within VS Code.

**Comment by Sertion** [comment]
Hello Enrico.

This did indeed change in the latest version and I did not take into account that the path could contain non-alphanumeric characters.

I'll see if I can make a quick fix here.

**Comment by Sertion** [comment]
A fix has been published to the marketplace. It can take a day or two until your editor automatically detects the new version.

Thank you for taking the time to report the issue!

**Comment by bolduz** [comment]
Thank you for your fast response 👍
