### ISSUE TITLE
Customizable status bar message format 

### ISSUE THREAD

**Issue by Sertion** [Sertion/vscode-gitblame#5]
Adding some customisation to the status bar message would be neat.

Info we currently have easy access to:
- Author
  - Name
  - E-mail
  - Timezone
- Commit
  - Hash
  - Time stamp
  - Commit message summary
  - What line number the line had before changes
  - Current line number
  - What filename the line originally came from (if we can use the `-M` and `-C` flags in the future)

Tools we can use:
- [Momentjs](https://momentjs.com/)
- `TextDecorator.toDateText`
- `TextDecorator.parseTokens` (`${token,options}`)

**Comment by Sertion** [comment]
Part of release 1.8.0.

**Comment by adeacetis** [comment]
By any chance, do you have documentation on this feature? Thanks. :)

**Comment by Sertion** [comment]
@adeacetis, there is a section for information about configurations in [README.md](https://github.com/Sertion/vscode-gitblame#configuration).
