### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by tolubydesign** [Sertion/vscode-gitblame#51]
- Issue Type: `Bug`
- Extension Name: `gitblame`
- Extension Version: `2.6.3`
- OS Version: `Linux x64 5.0.2-050002-generic`
- VSCode version: `1.32.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 35,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "onDebugResolve:chrome"
	}
}
```

**Comment by Sertion** [comment]
Hello Tolu.

I am unsure what is being reported here. What did you try to do and what happened?

**Comment by Sertion** [comment]
I'll close this now. If it's ever a problem again please get back to me.
