### ISSUE TITLE
Blaming still open and deleted file crashes the extension

### ISSUE THREAD

**Issue by dmitriismitnov** [Sertion/vscode-gitblame#54]
- Issue Type: `Bug`
- Extension Name: `gitblame`
- Extension Version: `2.8.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 43,
		"activateCallTime": 1,
		"activateResolvedTime": 15,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, watch #PATH_TO_FILE'"
		}
	]
}
```

**Comment by Sertion** [comment]
Hey dmitriismitnov.

Thank you for the report.

Where you looking at a file that was removed from the disk when this error occurred?

**Comment by Sertion** [comment]
Thank you for your report. A fix will be uploaded to the marketplace shortly.
