### ISSUE TITLE
Allow string manipulation in commitUrl

### ISSUE THREAD

**Issue by PapsOu** [Sertion/vscode-gitblame#55]
Hello,

First of all, your extension is very handy !

I've got a request about the way the extension generates links (commitUrl).

I need to upper case the project name to fit with a Phabricator instance.

The URL would be of this format : `https://my-phabricator-instance/rMYPROJECT4823fec0348bf0606bee42244425913eb2b00254`.

But setting `commitUrl` value as `https://my-phabricator-instance/r${project.name}${hash}` does not work (because project is named in lowercase : `myproject.git`.

Is it possible to allow string manipulation on tokens ?

**Comment by Sertion** [comment]
Hello PapsOu!

Thank you for the feature request.

I will see if I can figure something out.

**Comment by Sertion** [comment]
This will be released with Version 3.

There are two tokens that can be used by appending `|u` or `|l` to the end of a token.

`|u` will uppercase the value and `|l` will lowercase it.

**Comment by PapsOu** [comment]
Perfect it works great !

Thank you very much
