### ISSUE TITLE
time.custom is deprecated

### ISSUE THREAD

**Issue by Kyngo** [Sertion/vscode-gitblame#57]
Every time I open the plugin pop-up to get details on the commit, I see this message.

![](https://i.imgur.com/MOSakpf.png)

Running on macOS Mojave 10.14.5, installed from the extensions market.

**Comment by Sertion** [comment]
Hello Arnau. Thank you for the report. I will fix it as soon as possible.

**Comment by Sertion** [comment]
Patched version is uploaded to the marketplace.

**Comment by Kyngo** [comment]
That was fast! Great!
