### ISSUE TITLE
Extension host crashing when renaming file

### ISSUE THREAD

**Issue by pierznj** [Sertion/vscode-gitblame#59]
When I rename a file while a cursor is active inside that file, the vscode extension host crashes. I've used this extension for a couple of years and this is new behaviour. Only able to stop it by disabling the extension.

**Comment by Sertion** [comment]
Hello pierznj!

Thank you for the report!

That is weird and I recently changed how the extension stores the blame data together with the document. Looks like it had some unexpected side-effects.

I will not be able to look into what the problem might be for a few days, but will try to find some time next week.

**Comment by Sertion** [comment]
I had some time to look into this tonight but I am unable to rename files while still having an active cursor in the editing view.

Are you using an extension for this or is it an external application that renames the files?

**Comment by pierznj** [comment]
Thanks for looking into it. With respect to the active cursor, that may have been a red herring. It actually seems to happen when I rename a file, period.  I just re-enabled the extension, opened a file, then renamed it in the file list on the left hand side. I got the extension host crash pretty quickly, but it's not happening every time.

**Comment by Sertion** [comment]
I have been unable to recreate the issue on my Windows machine but found some things that could be tighter in the handling of the initial blaming of a file. [Here is a version with a potential fix](https://github.com/Sertion/vscode-gitblame/files/3513055/gitblame-3.0.2.vsix.zip). If you have the ability to try it out and report back that would be greatly appreciated.
