### ISSUE TITLE
Nothing shown in status bar if commit message line length is too long

### ISSUE THREAD

**Issue by thomaspugliese** [Sertion/vscode-gitblame#60]
If a commit message line length is too long to display in its entirety, nothing will be displayed at all in the status bar.  It would be much better to concatenate the message if possible.

**Comment by Sertion** [comment]
Hey thomaspugliese!

Are you using `commit.summary` in the `gitblame.statusBarMessageFormat` config option and this makes the status bar element disappear?

If this is the case there is not much I can do as vscode hides all status bar items that it can no longer fit in the status bar. I could add a parameter for `commit.summary` where you could configure the cutoff point yourself (a basic `substring`) but the vscode extension API does not allow me to _measure if a text will fit_ or not.

**Comment by thomaspugliese** [comment]
> Are you using commit.summary in the gitblame.statusBarMessageFormat config option and this makes the status bar element disappear?

Yes.

> the vscode extension API does not allow me to measure if a text will fit or not.

That sounds like the actual bug then.

**Comment by Sertion** [comment]
As of now there is nothing I can do here. It is being tracked in [vscode#6651](https://github.com/microsoft/vscode/issues/6651).
