### ISSUE TITLE
Add ability to set custom git blame parameters.

### ISSUE THREAD

**Issue by jyavenard** [Sertion/vscode-gitblame#62]
This will help with feature like https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt

which allows to ignore some revisions in the history.

gitLens already offers such feature. Would be nice to have gitblame do the same.

**Comment by Sertion** [comment]
Hello Jean-Yves!

Thank you for the feature request!

You can set this option by setting the file(s) you want to use as the value to the [git configuration](https://git-scm.com/docs/git-config) `blame.ignoreRevsFile`.

For more general parameters it is very easy to add something that changes enough of the output that it is either not parsable anymore or it would require extra code to appear in the usable tokens. For parameters that would require new tokens I would rather add them as specific features (like the _whitespace_ option)

I try to keep gitblame as scaled down as possible within reason and if more complex features is your thing GitLens is a great alternative.
