### ISSUE TITLE
GIT icon uncredited

### ISSUE THREAD

**Issue by Eonfge** [Sertion/vscode-gitblame#63]
The logo you are using belongs to the GIT Project, part of the Software Freedom Conservancy. There is no credit mention of this though. You should include the following link as an attribution:

https://git-scm.com/downloads/logos

You might also consider using a different logo altogether. The current logo is used by multiple different Git related projects and the current logo will make it hard for you to stand out.

**Comment by Sertion** [comment]
Hello Eonfge!

Thank you for the issue.

I will add a notice in the Readme for the next version.
