### ISSUE TITLE
[request] show the whole git commit in output window

### ISSUE THREAD

**Issue by calmisi** [Sertion/vscode-gitblame#68]
Now, after gettting the commit hash of the specific line, it can only specify the url+${hash} to see the entire git commit in the browser, which is fairly inconvenient.

Can you provide the support to just show the entire commit content in a seperate window of output? or like the peek window?

**Comment by Sertion** [comment]
Hello calmisi!

Sadly this information is not part of the output we get from the git blame command and would require additional commands and I want to keep the scope down.

If this is a feature you need I would recommend checking if [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) supports it.
