### ISSUE TITLE
Wrong URL for BitBucket commits

### ISSUE THREAD

**Issue by czanella** [Sertion/vscode-gitblame#69]
In projects hosted at BitBucket, the "View" button in the pop-up window leads to a broken URL. The URL provided by the Git Blame extension is something like this:

```
https://bitbucket.org/<username>/<project>/commit/<commit hash>
```

The correct URL should have `commits` instead of `commit`:

```
https://bitbucket.org/<username>/<project>/commits/<commit hash>
```

**Comment by Sertion** [comment]
Greetings.

You are looking for the feature built in #59.

It should be able to detect bitbucket.com origins by default. Perhaps you are using a self hosted setup?

Add the hostname to the `gitblame.pluralWebPathSubstrings` array and it should work. More info about the setting is available in the redme.
