### ISSUE TITLE
Documentation or text token is wrong

### ISSUE THREAD

**Issue by MisLink** [Sertion/vscode-gitblame#70]
[Message tokens section](https://github.com/Sertion/vscode-gitblame#message-tokens) shows tokens of author and committer email are `${author.email}` and `${committer.email}`, but [the code](https://github.com/Sertion/vscode-gitblame/blob/master/src/util/textdecorator.ts#L22,L30) shows they are `${author.mail}` and `${committer.mail}`. One of them must be wrong...

**Comment by Sertion** [comment]
Greetings MisLink.

Thank you for finding this. The right one is `.mail` in both cases. I will update this in the next version.
