### ISSUE TITLE
author.date and committer.date tokens don't work

### ISSUE THREAD

**Issue by chdsbd** [Sertion/vscode-gitblame#71]
It seems like some of the tokens are not working. I tried using committer.date and author.date because there was a warning saying time.custom was deprecated.

Here's the reproduction:

gitblame.statusBarMessageFormat
```
${author.name} ${time.ago}  ${committer.date} ${author.date} ${commit.hash_short,6}
```

actual
```
John Doe 4 days ago committer.date author.date 8af8co
```

expected
```
John Doe 4 days ago 2019-12-28 2019-12-28 8af8co
```

EDIT:
I think this was broken with v3.0, I installed 2.8.1 and now everything is working again with `${author.name} ${time.custom, YYYY-MM-DD}  ${commit.hash_short,6}`

**Comment by Sertion** [comment]
Greetings Christopher.

I don't believe that a version with `author.date` has ever been released to the vscode marketplace. It is an upcoming feature.

**Comment by tsheaff** [comment]
@Sertion when is this feature going to be launched on the VSCode Marketplace? It looks like this is already implemented in the code here, but just needs to be packaged and submitted?

**Comment by Sertion** [comment]
I need to find time to test everything. Sadly that takes a while these days since the number of features has ballooned a lot since the early days.
