### ISSUE TITLE
Linebreak in info popup

### ISSUE THREAD

**Issue by uranusjr** [Sertion/vscode-gitblame#76]
Would it be possible to put linebreaks in the `infoMessageFormat`? I tried some common values (e.g. `\n` `<br>`) and none works. Some quick googling says this probably needs some support from the plugin implementation. I have zero knowledge on VS Code extensions, but have some experience with TS and CSS, and might be able to help if this sounds like a good idea :)

**Comment by Sertion** [comment]
Hello Tzu-ping Chung! Thank you for the issue.

Right now VScode [does not support line breaks in notification dialogs](https://github.com/microsoft/vscode/blob/6ec6f9e3f4d17f0cef0480688a1f350b9141e567/src/vs/workbench/common/notifications.ts#L444). If they add support for line breaks in the future I will definitely add it then.
