### ISSUE TITLE
No blame info, `command '' not found` error

### ISSUE THREAD

**Issue by mikemaccana** [Sertion/vscode-gitblame#82]
Installing on current VScode 1.45.0 is giving:

> No info about the current line

Clicking the thorn (o|) icon produces the following error: 

![image](https://user-images.githubusercontent.com/172594/81670723-f0ade480-943f-11ea-99d9-310d836fe51c.png)

Other git blame plugins, like git lens, show `git blame` information ok.

**Comment by Sertion** [comment]
Hey Mike.

Thank you for the bug report.

Previously it was possible to disable commands on a status bar item by assigning the command to an empty string. Looks like that is no longer the case. I will aim to update later today.

**Comment by Sertion** [comment]
Pushed a fix to the marketplace. It can sometimes take a day or two to get it to appear but it is on its way!

Thanks again for the report!
