### ISSUE TITLE
Relative Path Token

### ISSUE THREAD

**Issue by bwathen** [Sertion/vscode-gitblame#87]
Hello, love the extension!  Helps out a ton with a large codebase 👍 

I have a feature request regarding the commit url.  Would it be possible to add a new token so the relative file path can be appended?  It'd be awesome to be able to directly open the current file using a URL anchor in the git blame commit link.

**Comment by Sertion** [comment]
Hey Ben! Glad you like the extension.

I think I have an idea how this could work.

**Comment by Sertion** [comment]
If you could try if [this version](https://github.com/Sertion/vscode-gitblame/files/4969499/gitblame-4.2.0-pre1.zip) works for you that would be great!

I have added a new `file.path` token for the `gitblame.commitUrl` configuration option.

**Comment by bwathen** [comment]
Awesome, worked perfectly! Thanks for the quick response 👍

**Comment by Sertion** [comment]
Thank you for verifying!

The new version is being uploaded. It can sometimes take a while for it to be available for everyone.
