### ISSUE TITLE
Feature Requests: URL configuration based on root folder

### ISSUE THREAD

**Issue by brennanMKE** [Sertion/vscode-gitblame#88]
I have some repos which are from GitHub and some are from internal Git repos and we have our own web interface for those. I have my `.gitconfig` set to use a different identity based on where the local directory is. I'd like to customize the URL based on the directory as well.

Can this be done with the current version of this extension.

Below is how I configure `.gitconfig` to use an alternative configuration for my GitHub repos.

```sh
[includeIf "gitdir:~/Documents/GitHub/**"]
	path = ~/Documents/GitHub/.gitconfig
```

**Comment by Sertion** [comment]
Hey Brennan! I am a bit unsure what you are requesting.

If you are looking for a way to customize settings in vscode by workspace folder pattern there might be an extension that will allow you to do that. It is also possible to have [custom settings by workspace](https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings).

If it has something to do with how git runs it should use any configurations you have. All the extension does is running git as the current user in the same folder where the file can be found. There is no magic beyond that.

I hope that this will help you figuring out a solution to your problem!
