### ISSUE TITLE
Nothing shown in bar

### ISSUE THREAD

**Issue by adambowles** [Sertion/vscode-gitblame#9]
Updated from 1.5 -> 1.8.0 this morning. Extension now shows nothing in the bar, while it was working before this weekend's updates

**Comment by Sertion** [comment]
Hey Adam.

I am unable to reproduce this issue in any of my test environments.

Have you tried shutting down vscode and launching it again?
What operating system are you using?
Is the git repository you are using old or contains a lot of commits? If so, have you waited for a few seconds to see if the information appears?

**Comment by adambowles** [comment]
- I have relaunched vscode, doesn't fix
- Using Fedora 22
- Repo has 653 commits, I've had vscode open for about 2 hours today

Here are my other extensions:

![image](https://cloud.githubusercontent.com/assets/10128574/25613834/954999f2-2f27-11e7-9f4e-073d2083ab62.png)

**Comment by adambowles** [comment]
Is it possible to install older versions so I can find the exact commit that broke?

**Comment by Sertion** [comment]
If you are willing to do some testing locally you can check out the code and run `npm install` followed by `npm install -g vsce`, checkout the commit you want to build and run `vsce package` to get an installable file that you can install using _Extension: Install from VSIX_.

**Comment by pftbest** [comment]
Hello, I have the same issue, will try to debug

**Comment by adambowles** [comment]
@Sertion thanks, I'm running locally compiled versions atm

**Comment by pftbest** [comment]
@Sertion, Found the issue, you have replaced `textdecorator` with `textDecorator` in commit https://github.com/Sertion/vscode-gitblame/commit/d616b1a6180c5285e5773a2051c448cfda142180

But the file name is still in lower case, so it can't find it.
This should be easy fix, but I can submit a pull request if you like.

**Comment by adambowles** [comment]
@pftbest I agree

Mine wouldn't even compile without that change, 

I guess you're developing on Windows @Sertion?

**Comment by Sertion** [comment]
A pull request would be welcomed. I will have some time in a few hours.

> I guess you're developing on Windows @Sertion?

Either a Mac or a Windows computer.

**Comment by vojtechhabarta** [comment]
Thanks for reporting and fixing this bug.

I think this type of errors can be prevented by using `forceConsistentCasingInFileNames` TypeScript compiler option.
