### ISSUE TITLE
[feature request] Inline view of gitblame

### ISSUE THREAD

**Issue by kramarz89** [Sertion/vscode-gitblame#94]
Hi,

Would really like to see the blame inline instead of bottom of the screen, would that be possible?

Thanks!

**Comment by Sertion** [comment]
Hello Adam.

Thank you for the request.

If this is a feature you would like I believe it is available in [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens).

**Comment by kramarz89** [comment]
Completely right, However I prefer yours :D Since that's the only feature I
need, and other gitlens features break stuff in my environment, had to
disable the addon completely

BR,
Adam

śr., 28 paź 2020 o 19:26 Albin Jacobsson <notifications@github.com>
napisał(a):

**Comment by Sertion** [comment]
I am not able to look into this for a while, but I will leave the ticket open.

I think [window.createTextEditorDecorationType](https://code.visualstudio.com/api/references/vscode-api#window.createTextEditorDecorationType) is used for this type of feature.

**Comment by f4n0** [comment]
Hi, 
It will be very useful for me too!
I've created a fork and created a WIP commit (as now it's working but it is not looking good/customizable) 

https://github.com/f4n0/vscode-gitblame/commit/b1580a4d97ea0c0e30f4e224a91baf844e5a4625

But the start I think will be that.
Let me know if this helps you!

**Comment by Sertion** [comment]
Hey f4n0. Looks good so far.

If you create a PR I can have a look and do some clean up.

If you want to do it yourself here are some comments:
* Please use a [`ThemeColor`](https://code.visualstudio.com/api/references/vscode-api#ThemeColor) for the decorator
* Please refrain from using global variables and please add `decorationType` to the `Extension` class' disposables
* I think it should be fine to add `setDecorations` to `PartialTextEditor`
* I would love a constant or something that gives a name to the magic number (1024) in `new Position(editor.selection.active.line, 1024),`

**Comment by f4n0** [comment]
I've modified it as you asked! (sorry but I'm not in the world of vscode extension developments!)

**Comment by andrewk-grabyo** [comment]
Excited to see this extension get the inline blame feature!

**Comment by JuanEL0** [comment]
This extension is really great, and like @kramarz89 I just want the inline blame so thanks @f4n0 for your time and effort

**Comment by Sertion** [comment]
I just uploaded the new version to the marketplace. It sometimes can take a few hours for it to appear for everyone.

If you want to enable the feature there is a setting.

Thank you to everyone for your help and to @f4n0 specifically for the great PR!

**Comment by JuanEL0** [comment]
Awesome extension, thank you @Sertion!!!
