### ISSUE TITLE
Stuck Waiting for git blame response (6.0.0)

### ISSUE THREAD

**Issue by pftbest** [Sertion/vscode-gitblame#95]
The last lines in the log are:
```
[ 16:31:09 | command ] git symbolic-ref -q --short HEAD
[ 16:31:09 | command ] git ls-remote --get-url origin
[ 16:31:09 | command ] git config branch.prod.remote
[ 16:31:09 | command ] git ls-files --full-name xxx.c
[ 16:31:09 | command ] git config remote.origin.url
```
However my repo is created with **git-svn** so it doesn't have any remotes.
I guess thats why this extension fails because it cant find a remote.

**Comment by Sertion** [comment]
Hey Vadzim!

Looks like a rare use-case that I have missed to take into consideration. Will look into a fix as soon as I am able.

**Comment by Sertion** [comment]
I've posted an update to the marketplace. Please report back if it did not solve the issue.

**Comment by pftbest** [comment]
Hello,

Thank you for looking at this! Unfortunately the version 6.0.1 does not help in my case, it still behaves the same way as the old version and gets stuck.

To help you diagnose the issue I have found a very small public svn repo which you can clone to reproduce the problem. Please try

```sh
sudo apt install git-svn

git svn clone https://svn.code.sf.net/p/log4j-advanced/code/trunk
```

Then open `trunk` directory in vscode and try to use git blame plugin.

**Comment by Sertion** [comment]
I misunderstood what the issue was. The repository was very helpful. I think I have solved it now. The new version is processing right now. It should be live any moment.

**Comment by pftbest** [comment]
Now it works fine, thank you!
