### ISSUE TITLE
Problem with making commitUrl from project.remote

### ISSUE THREAD

**Issue by tetafro** [Sertion/vscode-gitblame#98]
Hi. My current `project.remote` looks like this:
```
git@example.com:8080/my-project/my-repo
```

Is there any way to make commitUrl look like this?
```
https://example.com/projects/my-project/repos/my-repo/commits/0123abc...
```

**Comment by Sertion** [comment]
Greetings Dennis. Not right now to the best of my knowledge.

There is a token for grabbing parts of the `gitorigin.hostname`, but none for the path. Perhaps it could be added.

**Comment by Sertion** [comment]
A version with a new token has been uploaded and will be available shortly.

> `${gitorigin.path,n}` - the nth part of the git origin path (e.g. if the git origin is `https://github.com/ckb-next/ckb-next.git` `${gitorigin.path,1}` will return `ckb-next.git`

**Comment by tetafro** [comment]
Great, thanks.
If somebody is looking for self-hosted bitbucket commitUrl, this one works for me:
```
https://company.com/projects/${gitorigin.path,1}/repos/${gitorigin.path,2}/commits/${hash}
```
