### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tomerzaidler** [Sertion/vscode-gitblame#99]
- Issue Type: `Performance`
- Extension Name: `gitblame`
- Extension Version: `6.0.2`
- OS Version: `Linux x64 5.4.0-70-generic`
- VS Code version: `1.55.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/waderyan.gitblame-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Sertion** [comment]
Greetings Tomer!

In order to be able to check what has gone wrong here I need the cpuprofile-file mentioned in the report.

It could also be that git itself used a lot of CPU when blaming one or more files. If that is the case there is very little I can do to reduce that.

**Comment by Sertion** [comment]
Greetings again Tomer.

Without the cpuprofile there is nothing I can do here. I would love to check on what could be going wrong, but I can not. If you find the cpuprofile or this issue occurs again please don't hesitate to create a new issue or post a comment here.

For now I will close this issue.
